### ISSUE TITLE
Ubuntu 14.04启动后不能自动最小化到panel

### ISSUE THREAD

**Issue by XuQK** [librehat/shadowsocks-qt5#100]
ss-qt5 2.1.0
运行并成功连接后，窗口不会自动最小化（相关选项已勾选），此时点击“x”无反应，要在panel“右击-show”，然后点击“x”才会隐藏到panel。

**Comment by librehat** [comment]
能帮忙编译一下最新master分支的代码试试看吗？

**Comment by XuQK** [comment]
试了，这下不管怎么点叉都没反应了。。。我没编译过软件，操作步骤你看对不：
源码包解压到“~/Tool"
cd Tool/shadowsocks-qt5-master/
qmake INSTALL_PREFIX=/opt DEFINES+="UBUNTU_UNITY"
make
make install
过程中有几次缺少依赖，都解决了，无报错
然后在"Tool/shadowsocks-qt5-master/"中双击启动ss-qt5。

PS：源码包我直接在https://github.com/librehat/shadowsocks-qt5 右边点击的 
“Download ZIP”，应当没错吧。

**Comment by librehat** [comment]
你安装到/opt的话，应该从/opt下启动啊，直接命令行`/opt/bin/ss-qt5`

其他过程是没错的，能录屏给我看看么？

**Comment by jemyzhang** [comment]
已经提交pull request， 请review，使用time delay slot方法

**Comment by XuQK** [comment]
前半段从unity面板启动的那个是通过PPA安装的。后面命令行启动的是编译的最新 
分支。

**Comment by XuQK** [comment]
前半段从unity面板启动的那个是通过PPA安装的。后面命令行启动的是编译的最 
新分支。
