### ISSUE TITLE
xubuntu 15.04 最新版本启动后界面冻住

### ISSUE THREAD

**Issue by jemyzhang** [librehat/shadowsocks-qt5#101]
启动后界面冻住，不能正常显示，点击右上角关闭，无响应。
界面上右键弹出“工具栏”菜单，点选后崩溃退出
双击界面可以弹出配置界面，点击取消或者确定，崩溃退出。

版本是apt-get update到的。无debug信息

**Comment by jemyzhang** [comment]
拉取源代码测试了一下，发现增加unix: DEFINES += UBUNTU_UNITY后运行正常，看来launchpad里面的版本没有加这个编译。。。

**Comment by librehat** [comment]
launchpad用的就是debian里的rule编译的，选项应该有的。

**Comment by librehat** [comment]
查看了build log，UBUNTU_UNITY在DEFINES里的，可能是之前编译的（毕竟编译于Ubuntu 15.04发布之前几个礼拜）
