### ISSUE TITLE
无法连接使用camellia加密算法的服务器

### ISSUE THREAD

**Issue by testcaoy7** [librehat/shadowsocks-qt5#104]
虽然给出了camellia-128/192/256-cfb的选项，但是如果点击连接按钮的话，服务器的延迟数据会刷新一下，但无法真正地连上（连接按钮不变灰、断开连接按钮是灰色不可用状态）。

其他加密算法经测试没有问题。

**Comment by librehat** [comment]
呃，忘记这个加密方式了，之前一直没在libQtShadowsocks里实现，刚刚添加上。等下一个版本就好了。

**Comment by librehat** [comment]
`libQtShadowsocks` v1.5.1 released a moment ago and fixed this issue. Please wait for your Linux distribution's update.
