### ISSUE TITLE
A socket v4 connection was rejected.

### ISSUE THREAD

**Issue by suprsvn** [librehat/shadowsocks-qt5#105]
在ubuntu中使用shadowsocks-qt5，firefox在访问网络时，提示A socket v4 connection was rejected，并且不能链接上。请问该怎么解决，谢谢。

**Comment by archbishop** [comment]
同问

**Comment by librehat** [comment]
必须选socks v5

**Comment by librehat** [comment]
https://github.com/librehat/shadowsocks-qt5/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#firefoxchromechromium%E5%9B%BD%E4%BA%A7chromium%E5%A5%97%E5%A3%B3%E6%B5%8F%E8%A7%88%E5%99%A8

说的很清楚了。不要选HTTP代理，也不能是v4 socks
