### ISSUE TITLE
is there any way we can run the ss-qt5 in the backgroud?

### ISSUE THREAD

**Issue by jm0477** [librehat/shadowsocks-qt5#106]
do ss-qt5 has parameter that can allow we run in the background under Ubuntu14.10
now I only can run at the desktop.

so can I use command like: ss-qt5  config file.... ?

**Comment by librehat** [comment]
This is a GUI client and why do you want to run it at background?

Use command line ports in that case.

**Comment by jm0477** [comment]
Thanks librehat, I got the solution, thanks anyway. :)
I use the command line below:
sslocal -c config.json

**Comment by librehat** [comment]
Yes you can do that or use shadowsocks-libqss:

`shadowsocks-libqss -c config.json`

**Comment by jm0477** [comment]
thank you :)  librehat
this resolved my issue.
