### ISSUE TITLE
阻止重启关机动作？ xubuntu

### ISSUE THREAD

**Issue by jemyzhang** [librehat/shadowsocks-qt5#107]
ss-qt5在运行时，使用系统菜单关机/重启按钮，无法关机/重启。 命令行输入可以正常执行关机/重启动作。
将ss-qt5退出后，系统菜单关机/重启动作正常。

**Comment by librehat** [comment]
不应该有这个问题的，程序本身没有任何特别地阻止关机的函数
Ubuntu具体版本？

**Comment by jemyzhang** [comment]
我尝试过xubuntu 1410/1504 64bit
我以为是DBus的问题，但是看代码只有sendmsg，并没有block，还特意将send msg那段comment掉，没有效果

**Comment by librehat** [comment]
@jemyzhang DBus那里是异步操作不会block的。无法关机的时候ss-qt5里有激活的连接吗？

**Comment by jemyzhang** [comment]
有激活的链接！

**Comment by librehat** [comment]
Fedora 22无法重现该问题。
