### ISSUE TITLE
Whenever I start this shadowcks-qt5, my system has no response and breaks down.

### ISSUE THREAD

**Issue by robotcator** [librehat/shadowsocks-qt5#108]
my system : ubuntu 14.04 gnome

**Comment by librehat** [comment]
This shouldn't happen.

Start `ss-qt5` from terminal. Is there any output?

**Comment by robotcator** [comment]
it starts the ss, but when i try to connect it, the system has no respnse. i have come accross this problem several times. i still have no idea to solve it.

**Comment by librehat** [comment]
Do you install ss-qt5 from PPA? And are you sure the connection is valid?

**Comment by robotcator** [comment]
Yes, i install it from PPA. And i check it that the status is connected. So, what's the problem?

**Comment by librehat** [comment]
Maybe some conflicts with other applications? Because the issue you reported is not reproducible.

**Comment by robotcator** [comment]
i have no idea about that. i tried it just now, but my computer still had no response. i may look for some other software altertnative. than you anyway, i really appreciate it.
