### ISSUE TITLE
The connection was reset

### ISSUE THREAD

**Issue by lijiangwei1987** [librehat/shadowsocks-qt5#109]
log
Initialising ciphers...
Camellia-256/CFB (CAMELLIA-256-CFB) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 1080
Accept a local socket connection.
Connecting "www.baidu.com" at port 80 from "127.0.0.1" at port 43154 
Remote TCP socket state changed to QAbstractSocket::ConnectedState 
Remote TCP socket state changed to QAbstractSocket::ClosingState 
Remote TCP socket state changed to QAbstractSocket::UnconnectedState

**Comment by librehat** [comment]
This is not a reset. You'll have numerous TCP connections. But lots of them are short so they'll be closed very soon.
