### ISSUE TITLE
ubuntu 14.04LTS 浏览器配置代理服务器，老是显示连接被重置

### ISSUE THREAD

**Issue by lijiangwei1987** [librehat/shadowsocks-qt5#110]
日志：
Initialising ciphers...
Camellia-256/CFB (CAMELLIA-256-CFB) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 1080
Accept a local socket connection.
Connecting "www.google.com" at port 80 from "127.0.0.1" at port 45678 
Remote TCP socket state changed to QAbstractSocket::ConnectedState 
Remote TCP socket state changed to QAbstractSocket::ClosingState 
Remote TCP socket state changed to QAbstractSocket::UnconnectedState 

访问windows的 shadowsocks 可以访问google
访问ubuntu 的shadowsocks 浏览器显示连接被充值
我的 shadowsocks-qt5 有问题？

**Comment by librehat** [comment]
什么意思？你用什么去访问shadowsocks？你是共享给局域网其他设备吗？如果是的话本地地址要填0.0.0.0
