### ISSUE TITLE
Can not install on  Centos 7.1

### ISSUE THREAD

**Issue by lxdlife** [librehat/shadowsocks-qt5#111]
followed the wiki, add shadowsocks-qt 5 yum repo,and when i tried to install it ,the yum told me that because the lack of zbar,the ss-qt5 couldn't install.
any suggestion?

**Comment by librehat** [comment]
Sorry I forgot to mention. You have to enable this copr: http://copr.fedoraproject.org/coprs/mmraka/epel7-addons/

Wiki pages are updated to mention this copr repo.
