### ISSUE TITLE
linux版，希望能在已经有一个实例运行时，再次打开直接唤出正在运行的实例

### ISSUE THREAD

**Issue by s-kias** [librehat/shadowsocks-qt5#114]
不支持 elementary os 0.3 Freya的托盘，程序关闭后并不会退出，而是在后台运行
然后计算机睡眠再开启后，连接就断线了，我想要唤出程序发现无法唤出

**Comment by imzf** [comment]
这个问题我也遇到了很头疼，只能一直开着程序，希望能尽快修复elementary 的Application Indicator支持

**Comment by librehat** [comment]
@imzf 我可以把eOS的桌面环境加入到Application Indicator白名单里。你在终端下输入`echo $XDG_CURRENT_DESKTOP`然后把结果贴出来吧。

**Comment by s-kias** [comment]
@librehat 
```
~$ echo $XDG_CURRENT_DESKTOP
Pantheon
```

**Comment by librehat** [comment]
到时候2.3.1发布了之后麻烦反馈一下看看托盘图标是否正常

**Comment by s-kias** [comment]
@librehat 好的，谢谢！

**Comment by imzf** [comment]
@librehat 谢谢，现在已经可以显示 Indicator了
