### ISSUE TITLE
可否在连接编辑界面增加”向上，向下”这样调整顺序的功能？

### ISSUE THREAD

**Issue by ctexlive** [librehat/shadowsocks-qt5#118]
1. ss-qt5 2.3.0 目前增加了ss服务站点后，顺序就无法更改了，我的服务列表有几十个很长一串，想把速度快点的调整到前面，就很麻烦。

2. 用加密模式为table的时候程序会奔溃。

**Comment by librehat** [comment]
1. 可以点一下「延迟」来排序的啊。不过手动排序的功能会考虑加入的。
2. 在libQtShadowsocks 1.6.1里修复了这个问题。Linux用户更新libQtShadowsocks就可以了，Windows用户等下次Shadowsocks-Qt5一起更新

**Comment by ctexlive** [comment]
非常感谢。实际上我是想把自己最后增加的一个服务器提到最前面。
关于shadowsocks-libqss-v1.6.1-win64我正在测试，让其在win7 下做服务端，刚测试了几次，下大文件会自动退出。。。而且CPU占用很高。比较奇怪。等会报告
