### ISSUE TITLE
 可以有支持树莓派的版本吗

### ISSUE THREAD

**Issue by qqjt** [librehat/shadowsocks-qt5#119]
RT
树莓派2b，安装了ubuntu mate 系统，arm架构，貌似用不了ubuntu版本的。

**Comment by librehat** [comment]
自己编译就好了啊。

**Comment by firearasi** [comment]
Ubuntu mate arm 上编译成功，然而arch linux arm上怎么也安装不了

**Comment by librehat** [comment]
PPA supports armhf now

**Comment by GoodspeedWong** [comment]
树莓派用debian亲测没问题。
