### ISSUE TITLE
新增一个保存按钮

### ISSUE THREAD

**Issue by hnuzhoulin** [librehat/shadowsocks-qt5#123]
我现在在界面上删除老的一个配置，新建一个新的，、但是重启后又恢复成变化前的。。。

请问界面修改后害有没有保存之类的按钮啊？？

还有以前的版本支持开机自启动自动连接，但是现在的版本貌似不行喔。

我是Linux deepin，基于ubuntu14.04

**Comment by librehat** [comment]
以前也不支持开机自启，开机自启你要通过系统设置。自启连接在每个连接的编辑框里不是有选自动连接的吗？

你修改之后先退出程序再启动难道会变回去？？？

**Comment by iir910** [comment]
如果修改完后,没有正常退出（比如程序崩溃），新配置是不会保存的。。。所以加个手动保存也有意义。

**Comment by librehat** [comment]
@iir910 恩，打算加个保存项在File里了。不过崩溃应该提交问题来解决嘛……当然在解决之前加个保存按钮还是有用的

**Comment by hnuzhoulin** [comment]
多谢新加了手动保存功能

其实我想说的是，是不是每次都得在托盘图标那里右键退出才算是正常退出？

否则就保存啊？？我都是只是手动断开连接就直接shutdown的。。。。。

所以才有我的这个问题，每次开机都需要手动导入以此json

**Comment by librehat** [comment]
除了托盘那里，还有菜单栏点文件－退出也可以的。

直接shutdown应该也会保存的……因为保存功能是在程序退出时就会执行(在析构函数里)
