### ISSUE TITLE
ERR_EMPTY_RESPONSE in google chrome.

### ISSUE THREAD

**Issue by MuSamDu** [librehat/shadowsocks-qt5#124]
Sometimes it works well, but sometimes when i connected, and i connect it with ProxyOmega in Chrome, and it doesn't show anything but only a "ERR_EMPTY_RESPONSE" error and a reload button. And the log of the client is like that:
***
Initialising ciphers...
AES-256/CFB (AES-256-CFB) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 25301
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Accept a local socket connection.
Connecting "bit.ly" at port 80 from "127.0.0.1" at port 51273 
Connecting "bit.ly" at port 80 from "127.0.0.1" at port 51275 
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51277 
Connecting "google.com" at port 80 from "127.0.0.1" at port 51279 
A new TCP connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51281 
A new TCP connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51283 
A new TCP connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51286 
A new TCP connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51315 
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51317 
Connecting "google.com" at port 80 from "127.0.0.1" at port 51318 
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51330 
Connecting "google.com" at port 80 from "127.0.0.1" at port 51331 
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Accept a local socket connection.
Connecting "google.com" at port 80 from "127.0.0.1" at port 51339 
Connecting "google.com" at port 80 from "127.0.0.1" at port 51341 
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51346 
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51348 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51350 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51352 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51354 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51356 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51358 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51360 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51362 
A new TCP connection.
A new TCP connection.
Accept a local socket connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51364 
Connecting "github.com" at port 443 from "127.0.0.1" at port 51366 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51369 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51371 
A new TCP connection.
Accept a local socket connection.
Connecting "github.com" at port 443 from "127.0.0.1" at port 51373 
***

**Comment by librehat** [comment]
It looks like you're using an old version of `ss-qt5`, would you please update it and generate the log again?
