### ISSUE TITLE
编译失败在archlinux

### ISSUE THREAD

**Issue by helinb** [librehat/shadowsocks-qt5#125]
src/mainwindow.cpp: 在成员函数‘void MainWindow::onAbout()’中:
src/mainwindow.cpp:444:470: 错误：‘version’不是‘QSS::Common’的成员
 dowsocks-qt5'>GitHub</a></p>").arg(QStringLiteral(APP_VERSION)).arg(QSS::Common
                                                                     ^
Makefile:715: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1
make: *** 正在等待未完成的任务...

**Comment by librehat** [comment]
你必须要升级libQtShadowsocks版本，AUR里面的libQtShadowsocks和shadowsocks-qt5都太老了
