### ISSUE TITLE
如果已经连接上一个服务器,然后没有关闭,又去连另外一个服务器,但是端口是一样

### ISSUE THREAD

**Issue by xwj1003** [librehat/shadowsocks-qt5#127]
程序会提示,但是还是会崩溃.
连接其他服务器之前先判断一下.

**Comment by xwj1003** [comment]
win8.1 64bit
ss-qt5 2.3.2

**Comment by librehat** [comment]
无法重现，我就在Win8.1 64-bit测试的，没有问题。
你说的另外一个服务器的端口一样，是本地端口一样吧？我这里试了不会崩溃的。
