### ISSUE TITLE
2.3.2 版本在 openSUSE Tumbleweed 无法扫描屏幕上的二维码

### ISSUE THREAD

**Issue by gmg137** [librehat/shadowsocks-qt5#132]
我没测试其它版本，但在  openSUSE Tumbleweed 是不起作用的，不知道是不是我操作的方法有问题。通过选择二维码文件是可以的，但扫描就不行了。

**Comment by librehat** [comment]
目测和#55 重复

我试过在Ubuntu上扫描二维码是可以的，估计是zbar需要几个patch

**Comment by gmg137** [comment]
好，我试试用Ubuntu的zbar看行不行

**Comment by librehat** [comment]
恩，试验好了记得告诉我，如果真的这样的话我们再来排查是哪个patch

**Comment by smilingsun** [comment]
弱弱的问一句，Ubuntu下如何查看ss-qt5的版本？

**Comment by librehat** [comment]
菜单栏，关于

**Comment by smilingsun** [comment]
啊，我是Ubuntu15.04，并没有菜单栏啊，是我系统的问题吗？
而且我把Show Toolbar关掉了，也打不开了。。。

求解

![selection_060](https://cloud.githubusercontent.com/assets/4011348/10247889/ac3c6752-694e-11e5-8420-a883b15c1a80.png)

**Comment by smilingsun** [comment]
啊，我是Ubuntu15.04，并没有菜单栏啊，是我系统的问题吗？
其他应用程序，把鼠标移到左上角，是有菜单栏的，可是Shadowsocks-qt没有哎

求解

![selection_060](https://cloud.githubusercontent.com/assets/4011348/10247958/1ebed4d6-694f-11e5-8243-3ae44d34ee24.png)

**Comment by librehat** [comment]
https://github.com/shadowsocks/shadowsocks-qt5/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%92%8C%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95#%E4%B8%8D%E6%98%BE%E7%A4%BA%E8%8F%9C%E5%8D%95%E6%A0%8F
