### ISSUE TITLE
I can't change the config of connection in ubuntu14.04 gnome3

### ISSUE THREAD

**Issue by xxxzhi** [librehat/shadowsocks-qt5#133]
I want to change the config of shadowsock, but I can't connect the server after I change config. I exit the application, and restart it. I find that the config is not changed. Does anyone can help me?

**Comment by xxxzhi** [comment]
where is the config file saved?

**Comment by librehat** [comment]
`~/.config/shadowsocks-qt5/`

Run `ss-qt5` from terminal, does it crash?

**Comment by xxxzhi** [comment]
not crash. After I remove shadowsocks-qt5 and reinstall shadowsocks-qt5, I can change it, and save.  Thanks
