### ISSUE TITLE
延迟没有刷新

### ISSUE THREAD

**Issue by lizgyg** [librehat/shadowsocks-qt5#137]
第一次连接后延迟（毫秒）这个值是167，当我断开再重新连接还是167，换IP也一直是167。

**Comment by lizgyg** [comment]
是2.4.0版本

**Comment by librehat** [comment]
2.4.0版改了，连接的时候不会再去刷新延迟了（除非原本的延迟是未知的）

**Comment by librehat** [comment]
个人还不太确定这个要不要这样改动，如果不习惯的话我可以再改回来，每次连接都自动测一下

**Comment by librehat** [comment]
commit: 10ec39384e2e874247412d7d85e3ad02c335b920
