### ISSUE TITLE
Cannot fetch shadowsocks packages for ubuntu

### ISSUE THREAD

**Issue by ChristianVolk** [librehat/shadowsocks-qt5#142]
Hi, 

seems there are some packages missing? What should be done about it?

 sudo add-apt-repository ppa:hzwhuang/ss-qt5
> [works fine]

sudo apt-get update 

> W: Failed to fetch http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu/dists/precise/main/source/Sources  404  Not Found
> W: Failed to fetch http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
> W: Failed to fetch http://ppa.launchpad.net/hzwhuang/ss-qt5/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.

sudo apt-get install shadowsocks-qt5
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package shadowsocks-qt5

**Comment by librehat** [comment]
Which version of Ubuntu you're running?

**Comment by javaeryang** [comment]
@librehat my system is ubuntu 14.04 , but i get the same problem
