### ISSUE TITLE
can't open in opensuse tumbleweed with symbol lookup error 

### ISSUE THREAD

**Issue by amazingfate** [librehat/shadowsocks-qt5#144]
this is the log:
```ss-qt5: symbol lookup error: /usr/lib64/libQtShadowsocks.so.1: undefined symbol: _ZN5Botan18LibraryInitializer10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE```

this is the output of ```ldd /usr/lib64/libQtShadowsocks.so.1```:

        linux-vdso.so.1 (0x00007fffb13c5000)
        libbotan-1.10.so.0 => /usr/lib64/libbotan-1.10.so.0 (0x00007fd65c260000)
        libQt5Network.so.5 => /usr/lib64/libQt5Network.so.5 (0x00007fd65bf0e000)
        libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007fd65b84a000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fd65b4c8000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd65b2b1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd65af11000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fd65ad01000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007fd65a873000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd65a66f000)
        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007fd65a3df000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd65a1c1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fd659fb9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fd659da3000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd659aa1000)
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007fd659830000)
        libicui18n.so.55.1 => /usr/lib64/libicui18n.so.55.1 (0x00007fd6593c5000)
        libicuuc.so.55.1 => /usr/lib64/libicuuc.so.55.1 (0x00007fd65902e000)
        libpcre16.so.0 => /usr/lib64/libpcre16.so.0 (0x00007fd658dcb000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007fd658abc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd65c984000)
        libicudata.so.55.1 => /usr/lib64/libicudata.so.55.1 (0x00007fd6588bb000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fd65864f000)

I use the package @gmg137 built on obs.

**Comment by gmg137** [comment]
怀疑和最近更新的 libstdc++6-gcc5 有关，纯属猜测

**Comment by amazingfate** [comment]
It is the problem of libbotan. I've solved it by changing the build dep "libqt4-devel" to "libqt5-qtbase-devel" : https://build.opensuse.org/package/show/home:amazingfate/Botan
