### ISSUE TITLE
客户端 v2.4.0-win64停止工作BUG

### ISSUE THREAD

**Issue by Laevantain** [librehat/shadowsocks-qt5#149]
OS: Windows 8.1 pro x64
Client: ss-qt5-v2.4.0-win64

在程序内选择任意服务器后点击“测试延迟”会导致程序停止工作。但是使用管理员权限启动程序则不会出现这个问题。32位客户端不存在这个问题。windows反馈的错误信息如下：

问题签名:
  问题事件名称:	BEX64
  应用程序名:	ss-qt5.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	08ff0fd0
  故障模块名称:	WS2_32.dll
  故障模块版本:	6.3.9600.17415
  故障模块时间戳:	545042f4
  异常偏移:	000000000003f060
  异常代码:	c0000005
  异常数据:	0000000000000008
  OS 版本:	6.3.9600.2.0.0.256.48
  区域设置 ID:	2052
  其他信息 1:	339c
  其他信息 2:	339cbb5dceb24440d0b89776ec1218e0
  其他信息 3:	9512
  其他信息 4:	951293a8caf992ec74268573e845be2f

**Comment by librehat** [comment]
我本机Windows 8.1 64位测试没有任何问题。请检查一下是不是文件目录权限有问题？
