### ISSUE TITLE
I cannot start ss-gt5

### ISSUE THREAD

**Issue by loveyanbei** [librehat/shadowsocks-qt5#152]
I installed ss through PPA. I clicked the icon but it didn't response.When I opened the terminal and tried again. It says :
ss-qt5: symbol lookup error: ss-qt5: undefined symbol: _ZN3QSS10Controller4infoERK7QString

What's this ?
How can I solve it?

**Comment by librehat** [comment]
Did you install libQtShadowsocks via PPA as well? If not, please re-install `libqtshadowsocks` via PPA.
