### ISSUE TITLE
Ubuntu 14.04.2,用了几次以后，突然启动不了，没有界面显示。。

### ISSUE THREAD

**Issue by wangxj-nemo** [librehat/shadowsocks-qt5#154]
请问如何调试问题，如何解决？

**Comment by wangxj-nemo** [comment]
nemowang@nemowang-VirtualBox:/usr/bin$ ./ss-qt5 
libGL error: pci id for fd 18: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
段错误 (核心已转储)

是因为libGL的原因吗？但是可用的时候也有上面的错误。

**Comment by librehat** [comment]
不知道你这是怎么搞的，你要安装响应的-debug包，然后`gdb ss-qt5`在GDB里输入`r`启动然后看看错误信息。
