### ISSUE TITLE
compiling error: src/controllerthread.cpp:17:61: error: ‘info’ is not a member of ‘QSS::Controller’

### ISSUE THREAD

**Issue by swordtao** [librehat/shadowsocks-qt5#155]
hi librehat!
 
unexpextedly meets it when i compile the shadowsocks-qt5:

src/controllerthread.cpp:17:61: error: ‘info’ is not a member of ‘QSS::Controller’
     connect(&controller, debug ? &QSS::Controller::debug : &QSS::Controller::info, this, &ControllerThread::logAvailable);

i have to solve it like this:

connect(&controller,QSS::Controller::debug, this, &ControllerThread::logAvailable);

may be there need a patch  : )

**Comment by librehat** [comment]
How many times I have to say, please use **released** libqtshadowsocks!!!! DON'T use the code from git trunk
