### ISSUE TITLE
几个对使用舒适度和帮助文档的小改进建议

### ISSUE THREAD

**Issue by deepseer** [librehat/shadowsocks-qt5#156]
1. 流量设定。不同的SS的流量设定模式是不同的，不一定是按月限制，也有按日或者按年的。能否对这个问题进行细化？最好是在编辑代理的地方提供更多设置。
2. 能否把发布的exe文件按照32位和64位进行分别命名？ss-qt5-32和ss-qt5-64这样。其实根本原因是我上次下载了两个以后发生覆盖没注意到，导致把64位客户端带到32位电脑上无法运行了
3. 请在网页说明文档中明确说明，尚不支持UDP转发，需要UDP转发功能的请找其他客户端（比如libev的）。
4. 个人推荐用SocksCap64代替Proxifier，因为不用花钱
5. 关于有人提问“能否加入GFWList”的问题，可以再推荐几个其他选项，例如Shadowsocks，或者Chrome扩展导入AutoGFWList等等

**Comment by librehat** [comment]
1. 还有按日计流量的啊？年费的那种流量不也是按照一个月一个月统计的吗？不过这个功能不难做，下次会加上不同周期的。
2. 这个你自己建两个文件夹分开放吧，通行的办法32位和64位都是一样的名字
3. 应该是支持UDP转发的（之前libQtShadowsocks库写错了，请在下一个版本再测试一下）
4. Proxifier只是举个例子而已
5. GFWList增加了软件复杂度，不过「或许」会加入，目前没有计划。
