### ISSUE TITLE
暂时不支持PAC自动代理模式么？

### ISSUE THREAD

**Issue by fkpwolf** [librehat/shadowsocks-qt5#157]
Windows下面的这个功能很好用，希望能移植过来。

**Comment by librehat** [comment]
不支持

**Comment by fkpwolf** [comment]
有支持的计划么？

**Comment by librehat** [comment]
暂时没有计划。如果您有兴趣和时间帮忙，可以关注libQtShadowsocks项目，那个是ss-qt5的核心库

**Comment by mrdulin** [comment]
@librehat 你好，请问qt5，ubuntu系统，pac模式有没有什么曲线救国的方法，给点关键字～，谢谢
