### ISSUE TITLE
shadowsocks-qt5能在windows server 2003上使用吗?

### ISSUE THREAD

**Issue by zheng-xs** [librehat/shadowsocks-qt5#160]
我看了wiki, shadowsocks-qt5不支持xp, wibndows 2003支持吗? 我在64位windows 2003上使用时, 出现dll错误. 拷贝相应的dll文件也没有解决问题.

另外, shadowsocks-libqss 是否支持多个profile?

**Comment by librehat** [comment]
Windows 2003和XP内核差不多，所以不行的。

shadowsocks-libqss是个命令行程序，不支持复杂的功能
