### ISSUE TITLE
关闭后不能保存配置信息的问题咨询

### ISSUE THREAD

**Issue by Way-Ho** [librehat/shadowsocks-qt5#163]
shadowsocks-qt5在关闭之后不能保存配置信息，使用的操作系统是ubuntu15.04，应用的界面中没有手动保存的功能，如果是权限问题？请问应该如何配置？谢谢～
![2015-07-27 21 41 19](https://cloud.githubusercontent.com/assets/6374798/8907542/37cdd83a-34a9-11e5-9c2e-63726197856b.png)

**Comment by librehat** [comment]
你的菜单栏没有显示出来 #80
