### ISSUE TITLE
添加HTTP代理的支持

### ISSUE THREAD

**Issue by zheng-xs** [librehat/shadowsocks-qt5#164]
shadowsocks csharp版本好像能够同时支持socks5和https，shadowsocks-qt5能否实现这个功能？

**Comment by zheng-xs** [comment]
啥也没说就把问题关了

**Comment by librehat** [comment]
HTTP代理的功能在libQtShadowsocks `master`分支实现了，但是目前还有点问题，短期内ss-qt5是不会支持HTTP代理的。

**Comment by Samtoto** [comment]
是因为这个原因，不能够共享给局域网的其他设备么？

**Comment by librehat** [comment]
局域网其他的设备也要支持SOCKS5才可以，而且你添加配置的时候本地地址要填写0.0.0.0，默认是127.0.0.1只能本机用

**Comment by librehat** [comment]
libQtShadowsocks 1.7.0 beta加入了HTTP代理的支持，如果有空可以测试一下：https://github.com/librehat/libQtShadowsocks/releases/tag/v1.7.0-beta  因为ss-qt5的底层调用就是走libQtShadowsocks

**Comment by zheng-xs** [comment]
测试了一下，http代理模式下， 访问一般网站好像还行， 但是youtube，google都打不开， 不知道什么原因

**Comment by zheng-xs** [comment]
另外， shadowsocks-libqss.exe， 不能同时运行多个实例吗？

**Comment by librehat** [comment]
我测试Google和YouTube都是没问题的啊可以开多个，但是本地端口记得设置不一样的

**Comment by librehat** [comment]
Done
