### ISSUE TITLE
希望能提供过滤功能,对服务器的名称,IP,端口可以过滤.

### ISSUE THREAD

**Issue by xwj1003** [librehat/shadowsocks-qt5#167]
比如我有个50个节点,我想查找一个节点非常麻烦,需要慢慢滚动查找,太累了.希望提供一个搜索工具栏,可以过滤节点信息.

**Comment by lpssph** [comment]
一般用户没必要保留，保存那么多节点吧，，，留几个稳定的不就好咯。。。 本来不是有名称，ping，和最后使用排序了呢...

**Comment by xwj1003** [comment]
问题是我的节点真的过多,有些可能暂时不能用了,但是我还不想立刻删除. 
查找某个节点很不方便, 比如我只想连香港的, 我可以先过滤一下, 这样就会方便很多.
我感觉这个功能做起来应该不难.不想用的人可以不显示.
