### ISSUE TITLE
KDE无法关机

### ISSUE THREAD

**Issue by dirtycold** [librehat/shadowsocks-qt5#169]
openSUSE+KDE也有无法（注销/重启/关机）的问题，困扰了很久。不论有没有激活连接都是这个情况。

这里是提示的截图：
![ss-qt5-cancels-logout](http://wstaw.org/m/2015/08/09/ss-qt5-cancels-logout.png)

看到之前的几个问题报告，可能均标记为已关闭或是上游问题，而且都是gnome系的标题。不过还是重开一个，麻烦作者再排查一下。

**Comment by librehat** [comment]
问题是我无法重现这个问题啊，Fedora 22 Plasma 5.3 无法复现

**Comment by librehat** [comment]
麻烦试试编译一下master分支最新的shadowsocks-qt5，只能试试看是不是SIGINT和SIGTERM的问题

**Comment by dirtycold** [comment]
谢谢。刚刚重新编译了，可惜依然出现这个问题。

ps. 我把 MainWindow 的 closeEvent 重载去掉了，目测可以正常注销了。不知能不能有所帮助，但这貌似不科学… :-）

**Comment by librehat** [comment]
https://forum.qt.io/topic/38524/windows-cannot-terminate-process-when-i-m-shutting-down-or-restarting-computer/11

呃，你去掉closeEvent的重载就不能缩小到系统托盘了啊。你看看用回原来的2.4.1，但是不要缩小到托盘，看看能不能关机？上面这个链接说如果GUI全部hide了就可能不能关机……

**Comment by librehat** [comment]
最新的这个commit取消了重载，我估计这样问题某种意义上是「解决」了的。因为如果有一个QSystemTrayIcon在显示，整个程序是不会退出的。在使用Qt的系统托盘接口的桌面上都没有问题，但是在GNOME、Unity、LXDE这些桌面环境上，用的是AppIndicator，不重载closeEvent就会直接把程序关掉。还有待改进

**Comment by dirtycold** [comment]
用 2.4.1，在打开主窗口时注销，主窗口会隐藏，但还是不能注销。

使用最新的提交编译的版本，可以正常注销。

这么快就修复，真的非常感谢！

看来各桌面环境有不兼容的情况确实很麻烦阿，回头会在虚拟机上试试其他情况。

**Comment by librehat** [comment]
@dirtycold 所以可以确认就是重载closeEvent引起的。某些桌面环境会向所有程序发送closeEvent，因为我直接ignore掉了，所以这些桌面环境表示无法关机……

现在我想的办法是要在其他桌面环境也弄一个QEvent一直跑，不然关闭主窗口就会直接终止整个进程。

**Comment by librehat** [comment]
https://bugreports.qt.io/browse/QTBUG-32811
Qt已经在5.4.2和5.5.0修复了系统托盘的问题，所以刚刚的commit b2066162de9abcb0c78a48dd4fdeebe6f3ea339a 把Application Indicator改成只在5.4.2以下的版本使用，目前实在想不出好的办法，只能对用了Application Indicator的那部分用户说不要点X隐藏了，用系统托盘的菜单隐藏……

**Comment by dirtycold** [comment]
今天试了一个办法，不知能不能帮上忙。

首先保留 closeEvent 这样可以做到各环境通用。
然后注意到 QCloseEvent 有个 spontaneous () 方法， 判断时间来自于内部还是外部。而此处的目的是，若点击标题关闭按钮，主窗口隐藏；若是外部关闭信号，则退出程序运行。
因此在 closeEvent 重载中，要是这样判断，可能可以满足需要：
```
void MainWindow::closeEvent (QCloseEvent *e)
{
	if (e->spontaneous())
	{
		// qDebug () << "spontaneous";
		e->ignore();
		qApp->topLevelWindows().at(0)->hide();
	}
	else
	{
		// qDebug () << "not spontaneous";
		e->accept();
	}
}
```

不过刚刚仅在KDE4的环境下试了没啥问题。还没来得及在其他环境下测试...

**Comment by librehat** [comment]
Plasma 5里就算是鼠标点x也会判断spontaneous为true，虽然对Plasma 5没什么影响。

主要是要测试一下GNOME 和Unity

**Comment by dirtycold** [comment]
刚刚在 Unity 环境下试了一下，使用前面描述的方法，直接点 X 会隐藏主窗口，同时不会影响系统正常关机操作。明天会找 GNOME 再测试一下。

**Comment by librehat** [comment]
@dirtycold 你取消注释qDebug()看看。在Windows和Plasma 5下，点X的话spontanenous都是true……

**Comment by dirtycold** [comment]
可能是我理解的不对？点X是自发事件，因此不退出程序。而注销不是自发事件，因此退出程序。是这个意思吧

**Comment by librehat** [comment]
@dirtycold 文档说的很清楚了，spontaneous()在事件由程序外引发的就会判断为true，所以我的理解是用代码调用`close()`就不是spontaneous，而点X产生的事件是由task manager发送给程序的，所以spontaneous是true，同理关机的时候task manager也会发送关闭的请求。所以这个函数对本问题是没有帮助的。
你取消注释，就会发现点X的event也是spontaneous

**Comment by dirtycold** [comment]
关机的时候的事件 不是spontaneous 的吧？

**Comment by librehat** [comment]
我关机正常，所以没测试……难道关机不是spontaneous()？有空我再测测看。

**Comment by dirtycold** [comment]
update: 更新了KDE5环境。现在的症状是注销的时候卡在黑屏（当ss-qt5开启的时候）

**Comment by librehat** [comment]
@dirtycold 我刚刚又改了一下，麻烦再测试一下master分支？
