### ISSUE TITLE
shadowsocks-qt5无法做为goagent前置代理啊？大婶进来看看

### ISSUE THREAD

**Issue by lsnmx** [librehat/shadowsocks-qt5#170]
发issue前先在All issues中搜索是否已经有你要提交的问题。
GoAgent Version    : 3.2.3 (python/2.7.8 gevent/1.0.1 pyopenssl/0.13.1)
Uvent Version      : 0.3.0 (pyuv/0.10.11 libuv/0.10.26)
Listen Address     : 127.0.0.1:8087
Local Proxy        : 127.0.0.1:1080
GAE Mode           : https (TLSv1)

------------------------------------------------------
WARNING - [Aug 11 12:01:58] install root certificate failed, Please run as administrator/root/sudo
INFO - [Aug 11 12:02:46] 127.0.0.1:53266 "STRIP CONNECT autoproxy-gfwlist.googlecode.com:443 HTTP/1.1" - -
INFO - [Aug 11 12:03:29] 127.0.0.1:53283 "STRIP CONNECT connect.facebook.net:443 HTTP/1.1" - -
INFO - [Aug 11 12:03:47] 127.0.0.1:53284 "STRIP CONNECT connect.facebook.net:443 HTTP/1.1" - -
INFO - [Aug 11 12:03:47] 127.0.0.1:53285 "STRIP CONNECT connect.facebook.net:443 HTTP/1.1" - -

shadowsocks-qt5的日志显示（https://github.com/librehat/shadowsocks-qt5）
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.
An invalid socket connection was rejected. Please make sure the connection type is SOCKS5.

shadowsocks-CSHARP（https://github.com/shadowsocks/shadowsocks-windows）是可以做为GAE的前置代理的，也成功了可是shadowsocks-CSHARP的性能实在是太差了，吐槽一下，shadowsocks-qt5强很多想做GAE的前置代理使用不成功，怎么办大婶们！

[proxy]
enable = 1
autodetect = 1
host = 127.0.0.1
port = 1080

已经设置好了，要是shadowsocks-CSHARP没问题

**Comment by librehat** [comment]
目前不支持HTTP方式的代理，GoAgent的连接模式是HTTP的
