### ISSUE TITLE
Cannot build on ARM platform with ubuntu 14.04.

### ISSUE THREAD

**Issue by hotxboy** [librehat/shadowsocks-qt5#171]
I tried to install with ppa and  below command but failed.
sudo apt-get update
sudo apt-get install shadowsocks-qt5
I also tried to compile it but cannot download a package called libqtshadowsocks which u mentioned is mandate for the compiling process. I am using a AllWinner H3 dev board with Ubuntu installed which is ARM version of linux being ported.

**Comment by librehat** [comment]
PPA doesn't support non-x86 architectures. You need to compile libQtShadowsocks yourself at first. Check [Compiling](https://github.com/librehat/libQtShadowsocks/wiki/Compiling) wiki in `libQtShadowsocks`
