### ISSUE TITLE
When shadowsocks-qt5 is open, Gnome shell Power off dialog won' t open

### ISSUE THREAD

**Issue by xgdgsc** [librehat/shadowsocks-qt5#174]
I' m on archlinux with gnome shell 3.16.3-1 and shadowsocks-qt5 2.4.1-1, I have an weird issue that when shadowsocks-qt5 is open. Clicking on the menu Power off button won' t show the power off dialog. After I quit shadowsocks-qt5, clicking on the menu behaves normally. I' m not sure this bug belongs to which software.

**Comment by librehat** [comment]
Check #169
