### ISSUE TITLE
fail to install in centos7

### ISSUE THREAD

**Issue by bill2004158** [librehat/shadowsocks-qt5#175]
---> Package zbar.x86_64 0:0.10-21.el7.centos will be installed
--> Processing Dependency: libGraphicsMagick-Q16.so.3()(64bit) for package: zbar-0.10-21.el7.centos.x86_64
--> Processing Dependency: libGraphicsMagickWand-Q16.so.2()(64bit) for package: zbar-0.10-21.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libQt5Core.so.5()(64bit)
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libQt5DBus.so.5()(64bit)
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: qt5-qtbase
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libQt5Gui.so.5()(64bit)
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: botan
Error: Package: libQtShadowsocks-1.6.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: botan
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libQt5Network.so.5()(64bit)
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libbotan-1.10.so.0()(64bit)
Error: Package: zbar-0.10-21.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libGraphicsMagickWand-Q16.so.2()(64bit)
Error: Package: libQtShadowsocks-1.6.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: qt5-qtbase
Error: Package: shadowsocks-qt5-2.4.1-1.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libQt5Widgets.so.5()(64bit)
Error: Package: zbar-0.10-21.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: libGraphicsMagick-Q16.so.3()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by librehat** [comment]
What command did you use? You should use `yum` to install it and it should be able to find Qt5 and botan.

**Comment by Engine-Treasure** [comment]
I'm sorry..But I have the same problem just as his.I just copyed the content from "https://copr.fedoraproject.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo",does it matter?Then I followed the instruction.And I got the problem.

**Comment by librehat** [comment]
Have you enabled [EPEL](https://fedoraproject.org/wiki/EPEL) repo?
