### ISSUE TITLE
可以测试延迟，但是无法连接

### ISSUE THREAD

**Issue by JacobZHANG2015** [librehat/shadowsocks-qt5#176]
在Ubuntu 14.04LTS下安装后连接成功，测试延迟100多毫秒，但是使用Chrome+SwitchSharp无法连接，shadowsocks-qt5日志里不停地显示"Connecting "google.com" at port 80 from "127.0.0.1" at port 43009"诸如此类的消息，但是一直连接不上，可能是什么原因？该如何解决？谢谢！

**Comment by bugparty** [comment]
我也是这个问题

**Comment by liouvilles** [comment]
我的ubuntu14.04LTS也有这个问题,搞了半天了，还是连不上，用win7就能连上
