### ISSUE TITLE
Typo in add manual connection

### ISSUE THREAD

**Issue by ovitters** [librehat/shadowsocks-qt5#177]
I just tried out Shadowsocks-qt5. I noticed a typo in the "Profile editor"

To reproduce:
1. Connection -> Add -> Manually
2. Look at "Automation"

Currently reads: "Auto connection on applicatioin start"

Should read: "Auto connection on application start" (extra i in application)

**Comment by Skyjswolf** [comment]
I installed libbotan-dev and libbotan-1.10-1 but when i installed libshadowsocks it show me "Depends: libbotan-1.10-0 but it is not installable". I try to link libbotan-1.10-1 to libbotan-1.10-0 but it doesn't work. I'm using kubuntu15.10,what should i do to sovle this problem?
