### ISSUE TITLE
Default to AES-256-CFB as encryption method

### ISSUE THREAD

**Issue by ovitters** [librehat/shadowsocks-qt5#178]
When adding a new connection the encryption method currently defaults to "RC4-MD5". According to various documentation I read about shadowsocks, the recommended encryption method is AES-256-CFB. To encourage people using the best encryption method, please change the default in this dialog.

**Comment by librehat** [comment]
AES is not as fast as RC4-MD5, especially on low-end machines. Plus, RC4-MD5 is proven to be safe enough.
