### ISSUE TITLE
支持在 Unity 显示 Application Indicators

### ISSUE THREAD

**Issue by CzBiX** [librehat/shadowsocks-qt5#18]
希望能参考 [HOW TO: Application Indicators and LibNotify in QT5](http://ubuntuforums.org/showthread.php?t=2179045) 或使用 [libappindicator-qt](https://github.com/jarod/libappindicator-qt), 来实现在 Ubuntu Unity 显示 Application Indicators.

**Comment by librehat** [comment]
On Fedora 21 with fully upgrade (Qt 5.4), the system tray missing issue is fixed, at least fixed in Plasma 5

**Comment by CzBiX** [comment]
已升级到最新版本, 一切工作正常.
为任务栏图标和二维码的功能点 32 个赞.
