### ISSUE TITLE
Crash on Fedora 22, KF5, Qt 5.5

### ISSUE THREAD

**Issue by penguin12k** [librehat/shadowsocks-qt5#180]
shadowsocks-qt5.x86_64  2.4.1-1.fc22, 昨天更新完，今天一启动 shadowsocks-qt5 就崩溃了。
系统是 Fedora 22 x64 + KDE 。

>If ss-qt5 crashes and the only one instance mode is checked, you may need to manually delete /tmp/qipc_sharedmemory_ShadowsocksQt* and /tmp/qipc_systemsem_ShadowsocksQt*. Otherwise, ss-qt5 will complain that another instance is already running.

不确定有没有勾选 only one instance mode，并且 /tmp/ 下没有那两个文件。

求问如何解决？需要提供什么记录吗？

**Comment by librehat** [comment]
一启动就崩溃？你在终端底下运行看看什么情况。我在Fedora 23 x64 + KDE底下开发测试的没问题啊。

你可以尝试把原来的配置文件目录 `~/.config/shadowsocks-qt5` 删掉（记得做个备份），看看这样还会不会崩溃。

**Comment by penguin12k** [comment]
在终端下面运行 ss-qt5，弹出对话框提示“无法与先前运行的Shadowsocks-Qt5实例（PID: 2974）通讯。可能已经崩溃了。”
 之前确实有启动过 ss-qt5 并崩溃。

把 ~/.config/shadowsocks-qt5 删掉后重新在终端运行 ss-qt5 ，直接提示“段错误
(核心已转储)”并退出。~/.config/shadowsocks-qt5
文件夹重新生成了，里面只有一个 config.ini ，内容如下：

[General]
> HideWindowOnStartup=false
> OnlyOneInstance=true
> ToolbarStyle=4
>
> [Profile]
> size=0



在 2015年8月26日 上午1:40，Symeon Huang <notifications@github.com>写道：

**Comment by librehat** [comment]
Confirmed. 我估计是Qt 5.5导致的

**Comment by librehat** [comment]
I just confirmed this is a KF5 bug and should be fixed in next version.

**Comment by librehat** [comment]
更新一下Fedora，问题已经在最新的KDE Frameworks 5.13里修复了。

**Comment by penguin12k** [comment]
嗯，升级 KF5.13 确认已经能用了。thanks!
