### ISSUE TITLE
Shadowsocks-QT5+win10+SwitchyOmega+chome+SOCKS5重启电脑就不能正常使用！！

### ISSUE THREAD

**Issue by oe77** [librehat/shadowsocks-qt5#183]
上几天也是这样的平台Shadowsocks-QT5+win10+SwitchyOmega+chome+SOCKS5，但这两天不知什么回事不能用了！改了Shadowsocks-2.5.6+SwitchyOmega+http就变得一切正常！！！相当郁闷！！
![xshot-0017](https://cloud.githubusercontent.com/assets/12007315/9514788/94492c34-4ccf-11e5-901b-759b5ad88295.jpg)
![xshot-0018](https://cloud.githubusercontent.com/assets/12007315/9514789/944c5b02-4ccf-11e5-95c5-21c7244cac52.jpg)

**Comment by librehat** [comment]
看看SwitchyOmega的SOCKS协议是不是`SOCKS5`(SOCKS4是不支持的)
此外，Windows 10目前还不算正式支持（因为上游的Qt在5.5之后才正式支持的Windows 10）

**Comment by oe77** [comment]
是SOCKS5协议，重装完win10的电脑用qt5是无问题的，但重启过后就用不了！可能真的是你说的兼容问题

**Comment by librehat** [comment]
我刚刚特意装了Firefox试验了，目前发布的2.4.1版在Windows 10下是工作正常的，并没有出现问题。请再次确认你浏览器的设置。你也可以试试看Firefox + FoxyProxy是否可以工作正常

**Comment by librehat** [comment]
https://github.com/feliscatus/switchyomega/issues/544
