### ISSUE TITLE
[Ubuntu 15.10] Depend libbotan-1.10-0 error

### ISSUE THREAD

**Issue by Skywol** [librehat/shadowsocks-qt5#185]
I installed libbotan1.10-dev and libbotan-1.10-1 but when i installed libqtshadowsocks it show me "Depends: libbotan-1.10-0 but it is not installable". I try to link libbotan-1.10-1 to libbotan-1.10-0 but it doesn't work. I'm using kubuntu15.10,what should i do to sovle this problem?

**Comment by Skyjswolf** [comment]
apt-cache show libqtshadowsocks
Package: libqtshadowsocks
Priority: extra
Section: libs
Installed-Size: 225
Maintainer: Symeon Huang <hzwhuang@gmail.com>
Architecture: amd64
Version: 1.6.1-1~ubuntu15.10.1
Depends: libbotan-1.10-0, libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libqt5core5a (>= 5.4.0), libqt5network5 (>= 5.0.2), libstdc++6 (>= 4.8)
Filename: pool/main/libq/libqtshadowsocks/libqtshadowsocks_1.6.1-1~ubuntu15.10.1_amd64.deb
Size: 58908
MD5sum: d0288e1971ca9f66e13166ea4dee2da7
SHA1: 2ce2a9b5cd8a47fca2d216f3e8ec410825fca995
SHA256: f33668689b88ea54c621c9827306b5312882de98c4bf856cfea445307511364a
Description: A lightweight and ultra-fast shadowsocks library written in C++/Qt
Description-md5: 08020358c48f1eefd2739d958dc595ac

**Comment by librehat** [comment]
It looks like a wrong dependency during the generation of deb package (it should just depend on `libbotan-1.10`, not the version `1.10-0`). However, Ubuntu 15.10 is not officially released, and I don't have an environment to test it.

**Comment by Skyjswolf** [comment]
Uhm,I tried to install shadowsocks-qt5 from ppa in kubuntu15.04,it was still depending on libbotan-1.10-0,but the libbottan-1.10-0 could be installed.Maybe kubuntu 15.10 will remove the libbotan-1.10-0,so maybe you should fix the depend on libqtshadowsocks. Well, this occurred during the shadowsocks-qt5 installation,so I post it here =.=

**Comment by librehat** [comment]
The problem is not mine. As you can see from the control file: https://github.com/librehat/libQtShadowsocks/blob/master/debian/control, I didn't specify `botan-1.10-0`.

**Comment by librehat** [comment]
I think this is due to the changes happened in Ubuntu 15.10 since it's still in development cycle. I'll release libQtShadowsocks 1.7.0 and Shadowsocks-Qt5 2.5.0 in this month, then debs will get freshly built, which should resolve this issue.

**Comment by Skywol** [comment]
Thanks for your help .

**Comment by librehat** [comment]
Try update/upgrade, this should be resolved now.
