### ISSUE TITLE
shadowsocks-qt5运行的时候不能通过按钮关机

### ISSUE THREAD

**Issue by lingbop** [librehat/shadowsocks-qt5#186]
你好
发行版是debian8 使用xfce作业界面 lightdm管理 通过面板上的action buttons的log out/shutdown/reboot之类的均不能注销/关机
两台debian+xfce的计算机均无法这样关机 只能退出shadowsocks-qt5再按关机按钮 或者sudo poweroff关机
尚不知其他发行版是不是有这个问题 也不知道是不是偶然或者其他操作造成的问题
推测可能shadowsocks-qt5不响应xfce4关机按钮发出的退出进程的指令 可是我不知道这个log哪里可以看
望指教

**Comment by librehat** [comment]
参见#169 的讨论

能否测试一下master分支的代码是否解决了该问题？

**Comment by lingbop** [comment]
I recompile it and replace old version(it's from ppa). it works good. Logout problem got solved
Thx for fixing
