### ISSUE TITLE
[feature request] automatically disconnect previous connection when in local_addr/port conflict?

### ISSUE THREAD

**Issue by gregist** [librehat/shadowsocks-qt5#187]
It would make switching between servers a tad easier.

**Comment by librehat** [comment]
What if some people don't want to do that? This feature would make current behaviour different.

**Comment by gregist** [comment]
In a good way, I suppose?

When new users want to switch between servers, chances are these things happens: `let's switch to this shiny server, click connect->error prompt->oops, scroll scroll, locate current server->click disconnect->scroll back and click again->connect to new server.`

I honestly don't see the point of keeping those redundant steps in between.

**Comment by librehat** [comment]
Like sometimes people do want to keep different connections with different local ports. If this change is made, you wouldn't be able to tell if there was another connection running that used the same port.

However, I may add a new action, something like _override_ connect, which has the behaviour your suggested.

**Comment by gregist** [comment]
Thanks, I am looking forward to it. 

Maybe we can use a `port` column on the main interface to address your concerns.

**Comment by lpssph** [comment]
我也希望这样，这样切换节点将变得容易。
I hope it so, so switching node will become easier.
