### ISSUE TITLE
在ubuntu14.04lts 下崩溃

### ISSUE THREAD

**Issue by shenxs** [librehat/shadowsocks-qt5#192]
出现了一个严重的问题,之前一直没有这样的问题.
可以正常打开,但是非常容易崩溃(没有一分钟).莫名的就自己退出了
再次点击图标会有以下类似提示
`无法与先前运行的Shadowsocks-Qt5实例（PID: 21894）通讯。可能已经崩溃了。`
猜测可能和之前安装fcitx-qt5有关,这是在安装之后才出现的问题
fcitx-qt5安装过程请参看http://my.oschina.net/lieefu/blog/505363
不知道还需要哪些描述,暂时就这些吧

**Comment by librehat** [comment]
`export PATH="/home/lieefu/Qt5.5.0/5.5/gcc_64/bin":$PATH` 你如果设置了这一步，ss-qt5链接的Qt库就不一样了。你终端下
```
ldd `which ss-qt5`
```
贴一下结果

**Comment by shenxs** [comment]
linux-vdso.so.1 =>  (0x00007fff581db000)
	libqrencode.so.3 => /usr/lib/x86_64-linux-gnu/libqrencode.so.3 (0x00007f80f520a000)
	libQtShadowsocks.so.1 => /usr/lib/libQtShadowsocks.so.1 (0x00007f80f4fda000)
	libbotan-1.10.so.0 => /usr/lib/libbotan-1.10.so.0 (0x00007f80f4ae7000)
	libzbar.so.0 => /usr/lib/libzbar.so.0 (0x00007f80f48ad000)
	libappindicator.so.1 => /usr/lib/x86_64-linux-gnu/libappindicator.so.1 (0x00007f80f46a0000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f80f4064000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f80f3e13000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f80f35ea000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f80f336b000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f80f3027000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f80f29da000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f80f2334000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f80f2030000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f80f1e1a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f80f1a55000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f80f1845000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f80f146a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f80f1266000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f80f0ff2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f80f0dd4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f80f0bcc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f80f09b3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f80f06ad000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f80f0378000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f80f0123000)
	libv4l2.so.0 => /usr/lib/x86_64-linux-gnu/libv4l2.so.0 (0x00007f80eff15000)
	libindicator.so.7 => /usr/lib/x86_64-linux-gnu/libindicator.so.7 (0x00007f80efd06000)
	libdbusmenu-gtk.so.4 => /usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4 (0x00007f80efaf2000)
	libdbusmenu-glib.so.4 => /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4 (0x00007f80ef8d7000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f80ef625000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f80ef2b2000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f80eefaa000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f80eeda6000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f80eeb99000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f80ee993000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f80ee771000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f80ee466000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f80ee245000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f80ee030000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f80edde3000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f80edba7000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f80ed99f000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f80ed75a000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f80ed534000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f80ed2df000)
	libGL.so.1 => /usr/lib/nvidia-340/libGL.so.1 (0x00007f80ecf93000)
	libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007f80ecb8c000)
	libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007f80ec813000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f80f5416000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f80ec5f4000)
	libv4lconvert.so.0 => /usr/lib/x86_64-linux-gnu/libv4lconvert.so.0 (0x00007f80ec37b000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f80ec171000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f80ebf6e000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f80ebd5e000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f80ebb54000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f80eb94a000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f80eb747000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f80eb544000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f80eb332000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f80eb10f000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f80eaef4000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f80eacb6000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f80eaa13000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f80ea76a000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f80ea567000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f80ea35e000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f80ea155000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f80e9f2b000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f80e9d0f000)
	libnvidia-tls.so.340.76 => /usr/lib/nvidia-340/tls/libnvidia-tls.so.340.76 (0x00007f80e9b0c000)
	libnvidia-glcore.so.340.76 => /usr/lib/nvidia-340/libnvidia-glcore.so.340.76 (0x00007f80e6ef8000)
	libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007f80e568b000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f80e5487000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f80e5281000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f80e507a000)

**Comment by librehat** [comment]
动态链接库看起来没问题，你在命令提示符下运行`ss-qt5`，看看它崩溃的时候有些什么错误吧。

**Comment by shenxs** [comment]
段错误(核心已转储)

**Comment by librehat** [comment]
麻烦安装debuginfo，然后gdb下运行ss-qt5，崩溃之后输入`bt`把Backtrace贴上来。

**Comment by shenxs** [comment]
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe4dd5700 (LWP 3921)]
[New Thread 0x7fffde318700 (LWP 3922)]
[New Thread 0x7fffdd6d6700 (LWP 3923)]
[New Thread 0x7fffd7788700 (LWP 3924)]
[New Thread 0x7fffd6f87700 (LWP 3925)]
[New Thread 0x7fffd56c0700 (LWP 3926)]
[New Thread 0x7fffc3fff700 (LWP 3927)]
[Thread 0x7fffd6f87700 (LWP 3925) exited]
[Thread 0x7fffc3fff700 (LWP 3927) exited]

Program received signal SIGSEGV, Segmentation fault.
mod_mask_get_effective (mods=1, keymap=0x972c90) at src/state.c:1112
1112	src/state.c: 没有那个文件或目录.

**Comment by shenxs** [comment]
File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe4dd5700 (LWP 5750)]
[New Thread 0x7fffde318700 (LWP 5751)]
[New Thread 0x7fffddb17700 (LWP 5752)]
[New Thread 0x7fffd7788700 (LWP 5753)]
[New Thread 0x7fffd6f87700 (LWP 5754)]
[New Thread 0x7fffd56c0700 (LWP 5757)]
[New Thread 0x7fffc3fff700 (LWP 5758)]
*** Error in `/usr/bin/ss-qt5': free(): invalid size: 0x00000000006e43a0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff444fcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: 没有那个文件或目录.

**Comment by shenxs** [comment]
又不一样了

**Comment by librehat** [comment]
看不出任何有用信息，看看有没有人遇到类似问题的吧

**Comment by shenxs** [comment]
不知道为什么apt-get install 的版本无法使用了
卸载重新安装也不行,不是会崩溃而是根本打不开.
解决办法是自己编译得到ss-qt5,然后替换到/usr/bin/中去就好了

**Comment by librehat** [comment]
你是不是自己编译了Qt 5？如果你系统上有软件不是常规的apt-get安装的，那还请自己debug吧，有可能是错综复杂的依赖关系没玩好玩崩了。
