### ISSUE TITLE
Shadowsocks server DNS lookup failed: Invalid hostname

### ISSUE THREAD

**Issue by leirall** [librehat/shadowsocks-qt5#193]
Initialising ciphers...
AES-256/CFB (AES-256-CFB) initialised.
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 1090
Shadowsocks server DNS lookup failed: Invalid hostname
Connecting "124.251.61.14" at port 80 from "127.0.0.1" at port 60987 
DNS resolve failed: Invalid hostname
Connecting "124.251.61.14" at port 80 from "127.0.0.1" at port 60990 
DNS resolve failed: Invalid hostname

**Comment by librehat** [comment]
What's your local and server address?

**Comment by leirall** [comment]
Local Port？ 
server是用的ishadowsocks.com上面的免费账号

安装环境：ubuntu 14.04 Unity

p.s. 发现密码不对也提示连接成功，是否可告知调试的方法……或者还需要什么信息

**Comment by librehat** [comment]
密码不对当然会连接成功，连接只是SOCKS5连接上了（服务器端口正确），不代表Shadowsocks连接成功建立。local address，和port没关系，错误信息说的就是DNS解析失败了，无效的host名。

**Comment by leirall** [comment]
找到问题，server的标点是宽字符，因为提示连接成功一直以为dns error是不能resolve浏览器请求……把问题想复杂了，大神可以把Log提示人性化一点……

**Comment by librehat** [comment]
@leirall 连接成功是本地监听成功，之前说错了。不会检查服务器那边。这个还是得靠自己注意吧。
