### ISSUE TITLE
[!] v2.4.2 编译错误

### ISSUE THREAD

**Issue by MuSamDu** [librehat/shadowsocks-qt5#195]
我依照你的WIKI执行了：   

> dpkg-buildpackage -uc -us -b   

可到最后没有成功，提示：   

>dpkg-shlibdeps: 错误: no dependency information found for /usr/local/lib/libgobject-2.0.so.0 (used by >debian/shadowsocks-qt5/usr/bin/ss-qt5)
>Hint: check if the library actually comes from a package.
>dh_shlibdeps: dpkg-shlibdeps -Tdebian/shadowsocks-qt5.substvars debian/shadowsocks->qt5/usr/bin/ss-qt5 returned exit code 2
>debian/rules:6: recipe for target 'binary' failed
>make: *** [binary] Error 2
>dpkg-buildpackage: 错误: fakeroot debian/rules binary 提供错误退出状态 2   

麻烦解决一下，谢谢！

**Comment by librehat** [comment]
你什么发行版？

**Comment by MuSamDu** [comment]
Xubuntu 15.10

**Comment by librehat** [comment]
你稍等几天新版本发布后通过PPA源安装，自己编译出现的依赖问题请自行解决。
