### ISSUE TITLE
[2.5.0] sort by latency broken

### ISSUE THREAD

**Issue by gregist** [librehat/shadowsocks-qt5#196]
![2015-09-21_22-43-05](https://cloud.githubusercontent.com/assets/6292095/9995040/aa9f616e-60b2-11e5-90b8-0b3fa6c36f7b.png)

also that it would be nice to include a force connect button on toolbar.

**Comment by librehat** [comment]
There is no proper icon for force connect currently. I'll add it to toolbar once I found a nice icon.

**Comment by gregist** [comment]
I suggest this.

![network-force-connect](https://cloud.githubusercontent.com/assets/6292095/10010155/6d34da7c-6119-11e5-8b10-f9b11e767bda.png)

**Comment by librehat** [comment]
@gregist It would be identical when the button is disabled (grey).

**Comment by gregist** [comment]
well... I did not consider that.

How about this one?

![new canvas](https://cloud.githubusercontent.com/assets/6292095/10017774/cf928ecc-6163-11e5-887d-e47d25cbae30.png)

**Comment by librehat** [comment]
That makes it too different from other icons... maybe add a small thunder shape to the original icon?

**Comment by gregist** [comment]
I am afraid that's beyond my logo designing capacity. :wink:

**Comment by librehat** [comment]
;( Anyway, it's a low priority work. I'll fix the sorting issue in next minor update

**Comment by librehat** [comment]
Just a note that force connect won't be put into toolbar. There is no existing icon designed for that on Linux desktop. Adding an icon will break the theming on Linux.
