### ISSUE TITLE
2.5.0版经常崩溃，请开发者注意。

### ISSUE THREAD

**Issue by redfrog999** [librehat/shadowsocks-qt5#197]
昨天更新到2.5.0版后，使用和2.4.2版相同的config.ini，发现连上服务器之后，再次断开，连接另外一个服务器，会导致软件崩溃自己退出；另外，长时间运行后，没有断开操作，也会自动退出。

我是windows 8.1 系统，2.4.2和2.4.1在同一个系统下一路用下来非常稳定，2.5.0就出很多问题，希望开发者能debug，然后更新。

**Comment by redfrog999** [comment]
捣鼓了一下，自己解决了。原来是配置文件的问题，可以把导致程序不稳定的老的配置文件利用SS-QT5 2.5.0重新生成config.json，再次导入config.json程序生成config.ini就好了。希望能对遇到类似问题的提供参考。

**Comment by librehat** [comment]
旧版升级的时候你手动保存一下配置文件，然后重新打开应该就没问题了。2.5.0确实有对配置文件进行升级，不过不应该出现崩溃的。

**Comment by dd1994** [comment]
我第一次用这个软件，发现它没隔几分钟就崩溃一次啊，这是怎么回事呢？ @librehat 
我的系统是 Linux Mint 17

**Comment by dd1994** [comment]
看了下错误提示：
```
[1]    6579 segmentation fault  ss-qt5
```

**Comment by dd1994** [comment]
卧槽它过几分钟就出现段错误，C++ 果然太厉害。
