### ISSUE TITLE
为什么Ubuntu已经安装libqtshadowsocks 还提示没有安装

### ISSUE THREAD

**Issue by yuler** [librehat/shadowsocks-qt5#38]
The following packages have unmet dependencies:
 shadowsocks-qt5 : Depends: libqtshadowsocks (>= 1.2) but 1.2~ubuntu14.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by librehat** [comment]
我这里没有Ubuntu，只有Debian，Debian下用的规则都没有问题。

你先`sudo apt-get install libqtshadowsocks`，然后在终端下运行一下`apt-cache show libqtshadowsocks`把结果贴出来看看

**Comment by yuler** [comment]
Package: libqtshadowsocks
Priority: extra
Section: devel
Installed-Size: 245
Maintainer: Symeon Huang <hzwhuang@gmail.org>
Architecture: amd64
Version: 1.2~ubuntu14.04.1
Depends: libbotan-1.10-0, libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libqt5concurrent5 (>= 5.0.2), libqt5core5a (>= 5.0.2), libqt5network5 (>= 5.0.2), libstdc++6 (>= 4.1.1)
Filename: pool/main/libq/libqtshadowsocks/libqtshadowsocks_1.2~ubuntu14.04.1_amd64.deb
Size: 60776
MD5sum: 8b6abecc4504da790875df6410674bf5
SHA1: fd4999ab2a2a0cf7028c8f0ba0dc809160942720
SHA256: 01391fc329f55707493945f4d92bcc78e4ba640aee6302aa008c0b7491b7f16e
Description-en: A Shadowsocks library written in C++/Qt5
Description-md5: a48fd430d5e661e521b59b488f446495

**Comment by librehat** [comment]
我把PPA上的libqtshadowsocks版本号变更了一下，现在是1.2-1~ubuntu14.04.1了，麻烦再试试
`sudo apt-get update`
`sudo apt-get install shadowsocks-qt5`

**Comment by yuler** [comment]
恩，现在可以安装了
