### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "xcb".

### ISSUE THREAD

**Issue by SmilingSun** [librehat/shadowsocks-qt5#39]
I can't understand the section very well, 
https://github.com/librehat/shadowsocks-qt5#dependencies
does it mean I need to install Qt?

But after installing under the instruction of 
https://github.com/librehat/shadowsocks-qt5#ubuntu
I got these staff in my terminal: 
```
sunjizu@HP-Pavilion-g4-Notebook-PC:~/Documents/rdesktop$ ss-qt5
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)
````
What should I do?

My environment: 
* Ubuntu 14.04 LTS 64bit
* Locating xcb?
```
sunjizu@HP-Pavilion-g4-Notebook-PC:~/Documents/rdesktop$ locate libxcb.so.1
/opt/teamviewer/tv_bin/RTlib/libxcb.so.1
/opt/teamviewer/tv_bin/RTlib/libxcb.so.1.1.0
/usr/lib/libxcb.so.1
/usr/lib/i386-linux-gnu/libxcb.so.1
/usr/lib/i386-linux-gnu/libxcb.so.1.1.0
/usr/lib/x86_64-linux-gnu/libxcb.so.1
/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
```

**Comment by librehat** [comment]
Please check if you've installed `libqt5gui5` package. Also, is your system up-to-date?

`sudo apt-get update`
`sudo apt-get dist-upgrade`

**Comment by librehat** [comment]
Just a quick clarification. The error message indicates it can't find `libqxcb.so` not `libxcb`. `libqxcb.so` is a Qt platform plugin of xcb. It should located in `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/`

**Comment by SmilingSun** [comment]
```
sunjizu@HP-Pavilion-g4-Notebook-PC:~$ ls /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/ 
libqeglfs.so  libqkms.so  libqlinuxfb.so  libqminimalegl.so  libqminimal.so  libqoffscreen.so  libqxcb.so
```
And error still occurs:
```
sunjizu@HP-Pavilion-g4-Notebook-PC:~$ ss-qt5
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

I'm really looking forward to run it under my Ubuntu, thx!

**Comment by librehat** [comment]
Thank you, but I can't reproduce the issue on my machine. I've installed Ubuntu 14.04, but everything works fine.
![out](https://cloud.githubusercontent.com/assets/1279432/5746232/2e6d26ae-9c26-11e4-934c-8b38971a6ee8.gif)

**Comment by SmilingSun** [comment]
问题应该出在**115网盘（Linux版）**上。

在安装Xware  Desktop的时候，提示跟115网盘冲突，根据这里的说明，
http://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=9508
修改了115的相关QT配置文件。

不仅Xware Desktop好了，Shadowsocks-QT也能启动了。

**Comment by SmilingSun** [comment]
问题应该出在**115网盘（Linux版）**上。

在安装Xware  Desktop的时候，提示跟115网盘冲突，根据这里的说明，
http://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=9508
修改了115的相关QT配置文件。

不仅Xware Desktop好了，Shadowsocks-QT也能启动了。

**Comment by SmilingSun** [comment]
问题应该出在**115网盘（Linux版）**上。

在安装Xware  Desktop的时候，提示跟115网盘冲突，根据这里的说明，
http://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=9508
修改了115的相关QT配置文件。

不仅Xware Desktop好了，Shadowsocks-QT也能启动了。

**Comment by SmilingSun** [comment]
问题应该出在**115网盘（Linux版）**上。

在安装Xware  Desktop的时候，提示跟115网盘冲突，根据这里的说明，
http://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=9508
修改了115的相关QT配置文件。

不仅Xware Desktop好了，Shadowsocks-QT也能启动了。

**Comment by SmilingSun** [comment]
问题应该出在**115网盘（Linux版）**上。

在安装Xware  Desktop的时候，提示跟115网盘冲突，根据这里的说明，
http://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=9508
修改了115的相关QT配置文件。

不仅Xware Desktop好了，Shadowsocks-QT也能启动了。
