### ISSUE TITLE
gnome shell里过段时间窗口就隐藏了？

### ISSUE THREAD

**Issue by xgdgsc** [librehat/shadowsocks-qt5#41]
打开之后过段时间窗口就隐藏了， 托盘在窗口在的时候虽然看不见icon，但是可以使用，窗口消失之后托盘还在，就是gnome里看不见icon找起来麻烦。再启动一次之后会出现一个新的进程。环境是archlinux, shadowsocks-qt5-0.8.0-1-x86_64。

**Comment by xgdgsc** [comment]
发现切换workspace的时候就会消失，因为gnome shell托盘看不到qt程序的icon，能不能默认把这个功能关了？

**Comment by librehat** [comment]
杂项设置里面不是有么。
