### ISSUE TITLE
如果密码是粘贴的话，无法保存

### ISSUE THREAD

**Issue by DrakeLeung** [librehat/shadowsocks-qt5#42]
另外，密码手动输入的话，可以保存。

Ubuntu 14.04 @librehat

**Comment by librehat** [comment]
无法重现，我刚刚Debian下试了一下粘贴没有任何问题。

你用的什么系统？

**Comment by DrakeLeung** [comment]
不好意思，忘记说了- -  Ubuntu 14.04。

**Comment by librehat** [comment]
#29 和你这个有一点点像，都是密码框的问题，而且都是Ubuntu下才有。估计是发行版打包引起的，因为无法在其它发行版和操作系统上重现。
