### ISSUE TITLE
libQtShadowsocks 模式无法使用 RC4-MD5 算法

### ISSUE THREAD

**Issue by CzBiX** [librehat/shadowsocks-qt5#45]
刚安装的最新的 0.8.1, Ubuntu 14.10.
使用 libQtShadowsocks + RC4-MD5 时, 在创建了几个网络连接之后就会 crash.
终端里提示: `[1]    30530 segmentation fault  ss-qt5`

**Comment by librehat** [comment]
RC4-MD5 will result in crashes in 64-bit machine. This is due to the unaligned memory operation in `botan` library.

I'll bundle a refined RC4-MD5 class in next version of `libQtShadowsocks`. https://github.com/librehat/libQtShadowsocks/issues/12

**Comment by librehat** [comment]
The crash is fixed in libQtShadowsocks. I'll leave this issue as a reference which will be closed once new version of `ss-qt5` is pushed into all platforms.

**Comment by librehat** [comment]
Fixed.
