### ISSUE TITLE
程序 crash 后无法启动

### ISSUE THREAD

**Issue by CzBiX** [librehat/shadowsocks-qt5#46]
终端里提示 `Abort. Another instance of Shadowsocks-Qt5 is already running.`
尝试手动删除 `/tmp/qipc_sharedmemory_shadowsocksqt...` 后才能正常启动.

**Comment by librehat** [comment]
Hmm. The crash stopped application from releasing shared memory, which causes this issue.

I'll add an option to control whether the `single instance` should be used.
