### ISSUE TITLE
Ubuntu Unity 启动ss-qt5后看不到程序窗口的内容

### ISSUE THREAD

**Issue by foocie** [librehat/shadowsocks-qt5#48]
![2015-01-22 17 14 04](https://cloud.githubusercontent.com/assets/10651153/5853051/4dcb0ef0-a25a-11e4-84f2-653056dcdb8d.png)

第一次启动正常，然后再启动就只能看到窗口下面的内容，程序窗口的内容都无法看到

**Comment by foocie** [comment]
好像是启动后自动隐藏主窗口导致的，刚才删除了配置文件，然后打开程序就正常了

**Comment by DrakeLeung** [comment]
@foocie 我也遇到这个bug。你通过点击屏幕左上角的小图标，来打开ss，这样就正常了。

**Comment by librehat** [comment]
Please disable system tray on Ubuntu Unity. The system tray icon doesn't work well in Ubuntu Unity.

**Comment by foocie** [comment]
已经解决了。
![2015-01-23 08 44 51](https://cloud.githubusercontent.com/assets/10651153/5867976/0b13c654-a2de-11e4-9013-c2454430f993.png)

如果同时选中“启动后自动隐藏主窗口”和“使用系统盘”就会出现这种情况。
单击左上角的小图标可以再显示窗口，这样就可以把选中的选项取消，显示就正常了。
