### ISSUE TITLE
请问后端和自定义参数一定要填吗？

### ISSUE THREAD

**Issue by Tanlet** [librehat/shadowsocks-qt5#49]
我的Android使用正常，但是在相同参数下，在ubuntu中shadowsocks-qt5提示设置错误的弹框。请问这两个参数是什么？如何填写？还有Unity的显示问题，一定要在master分支才可以解决吗？

**Comment by librehat** [comment]
For Unity and Plasma 5, uncheck "use system tray" option in Misc tab.

Choose libQtShadowsocks as your backend, then you don't need to supply any backends or arguments.

**Comment by Tanlet** [comment]
但是，我的VPS使用的是python后端，还是选后端类型为libQtShadowsocks吗？也不行！

Remote socket error: Connection refused

**Comment by Tanlet** [comment]
Sorry！一个低级失误，把端号写错了。我认为应该直接默认后端为libQtShadowsocks，不然这个参数很易让人误会。至少我认为这个是与后台的类型一样。

**Comment by librehat** [comment]
Add `ss-qt5` to your session auto-start applications just like what you do to all other applications.

Linux is not Windows, an application should never take charge of **auto-start**.
