### ISSUE TITLE
Ubuntu下关闭ss-qt5再启动后提示Another instance is already running

### ISSUE THREAD

**Issue by dozaza** [librehat/shadowsocks-qt5#50]
关闭之后程序确实退出了，但是想再启动的时候提示 already running。

ps aux | grep ss-qt5，没有找到相应的进程。不知道是否是bug，如果是我操作不当，麻烦能告诉我下该如何正确使用吗？

谢谢！

**Comment by librehat** [comment]
If `ss-qt5` exits abnormally, the shared memory won't be released, which causes this issue.

Start `ss-qt5` from terminal, see if there's any error messages when it exits.

**Comment by s-kias** [comment]
i have this problem too.
While i start `ss-qt5`from terminal, it says `Abort. Another instance of Shadowsocks-Qt5 is already running.`. If I `killall ss-qt5` it says `ss-qt5: no process found`

**Comment by librehat** [comment]
@s-kias Did the previous `ss-qt5` exit normally?

**Comment by s-kias** [comment]
@librehat No. I wanted to minimize it into system tray, but it vanished that I can't call it out. So I tried `killall ss-qt5` ......

**Comment by librehat** [comment]
Damn Ubuntu... The system tray problem is fixed in Qt 5.4 I believe. For now, I have to spare some time to use libappindicator to fix this issue on Ubuntu.

**Comment by librehat** [comment]
It should be fixed with latest commit.

**Comment by SmilingSun** [comment]
I'm using v0.9.2 under Ubuntu 14.04, the same happens.

![sunjizu hp-pavilion-g4-notebook-pc _132](https://cloud.githubusercontent.com/assets/4011348/6546439/9776b04c-c5ee-11e4-95f6-a9948b6eef06.png)

**Comment by librehat** [comment]
The last instance might exit with problems (crashed). You need to delete the shared memory files under `/tmp/`
