### ISSUE TITLE
[opensuse]qmake failed

### ISSUE THREAD

**Issue by verrazanof** [librehat/shadowsocks-qt5#51]
opensuse 13.2

$ qmake INSTALL_PREFIX=/usr
"Project ERROR: Package QtShadowsocks not found"

I'm sure I have installed all dependences(qt5-qtbase, botan, libQtShadowsocks,qrencode).

**Comment by librehat** [comment]
Including development package of `libQtShadowsocks`? (`libQtShadowsocks-devel`)

Check `/usr/lib64/pkgconfig/` or `/usr/lib/pkgconfig/`, is there a `QtShadowsocks` directory?

**Comment by verrazanof** [comment]
I can't find the Qtshadowsocks directory.
So i tried to reinstall libQtShadowsocks.
But there is a new error:

$  make && make install 
cd lib/ && /usr/bin/qmake /home/verf/下载/libQtShadowsocks-master/lib/libQtShadowsocks.pro INSTALL_PREFIX=/usr -o Makefile.libQtShadowsocks
cd lib/ && make -f Makefile.libQtShadowsocks 
make[1]: Entering directory '/home/verf/下载/libQtShadowsocks-master/lib'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_WEBKIT -DQSS_LIBRARY -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include -I/usr/local/include/botan-1.10 -I. -o address.o address.cpp
In file included from address.cpp:28:0:
address.h:41:21: error: expected ‘,’ or ‘...’ before ‘&&’ token
     Address(Address &&) = default;//force the generation of default move constructor
                     ^
address.h:41:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     Address(Address &&) = default;//force the generation of default move constructor
                           ^
address.h:41:27: error: invalid constructor; you probably meant ‘QSS::Address (const QSS::Address&)’
Makefile.libQtShadowsocks:324: recipe for target 'address.o' failed
make[1]: *** [address.o] Error 1
make[1]: Leaving directory '/home/verf/下载/libQtShadowsocks-master/lib'
Makefile:40: recipe for target 'sub-lib-libQtShadowsocks-pro-make_default-ordered' failed
make: *** [sub-lib-libQtShadowsocks-pro-make_default-ordered] Error 2

**Comment by librehat** [comment]
There is no `-std=c++0x` in your `gcc` line. Are you sure you did it correctly?

```
qmake
make
make install
```

Also, please ensure you're using Qt5's qmake instead of Qt4's.
