### ISSUE TITLE
Failed to compile in Arch Linux

### ISSUE THREAD

**Issue by hellolj** [librehat/shadowsocks-qt5#53]
username:shadowsocks-qt5-0.9.0/ $ qmake INSTALL_PREFIX=/usr 
username:shadowsocks-qt5-0.9.0/ $ make                                                        
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DAPP_VERSION=\"0.9.0\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I. -isystem /usr/include/qtshadowsocks -isystem /usr/include/botan-1.10 -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtCore -I. -I. -o ss_process.o src/ss_process.cpp
src/ss_process.cpp: In constructor ‘SS_Process::SS_Process(QObject*)’:
src/ss_process.cpp:13:29: error: ‘runningStateChanged’ is not a member of ‘QSS::Controller’
     connect(qssController, &QSS::Controller::runningStateChanged, [&] (bool running) {
                             ^
Makefile:412: recipe for target 'ss_process.o' failed
make: *** [ss_process.o] Error 1

**Comment by librehat** [comment]
You need `libQtShadowsock` >= 1.4!
