### ISSUE TITLE
QR Code isn't scanned on Fedora 21, 22, OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by librehat** [librehat/shadowsocks-qt5#55]
Fedora 21, Plasma 5.2.

Need to invest when I'm not busy...

**Comment by librehat** [comment]
Not a plasma 5 issue. It's a zbar issue, it can't decode screenshoot. But can only decode "pure" QR code image.

**Comment by gmg137** [comment]
我把 ubuntu 的 libzbar0 安装到 openSUSE 还是不行。

**Comment by librehat** [comment]
不过只能是zbar的问题了啊，我之前排查过，截图什么的都没问题，而且Windows下正常。太奇怪了

**Comment by gmg137** [comment]
是不是在编译环节使用的zbar也得是打了补丁的？？？另外我是在浏览器打开带二维码的网页或截图后用图片浏览器打开图片，然后再选择扫描屏幕二维码选项的，方法不会有问题吧！

**Comment by librehat** [comment]
方法没问题，只要二维码图片露出来就可以了。

和编译时的包应该没关系的

**Comment by gmg137** [comment]
那真没解决思路了，，，话说ss-qt有没有调试模式？

**Comment by librehat** [comment]
@gmg137 要调试的话在Qt Creator里打开project然后Debug，调试不出什么东西的……

**Comment by gmg137** [comment]
好吧！反正这个功能可有可无，还是不折腾了

**Comment by gmg137** [comment]
最近一次系统更新后，托盘图标竟然可以正常显示了，应该是 GNOME 把问题修复了
