### ISSUE TITLE
系统托盘图标没有出现。GNOME 3.14.2 ( Debian 8 )

### ISSUE THREAD

**Issue by tonghuix** [librehat/shadowsocks-qt5#56]
如题，启动以后，并没有在托盘区域有图标出现。

**Comment by librehat** [comment]
See https://bugreports.qt.io/browse/QTBUG-32811?focusedCommentId=272624&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-272624

>So far I don't know of a way that Gnome 3 can be "fixed" because they purposely are hiding most tray icons. But in some versions (not all!), it shows up in the notification area at the bottom of the screen.
