### ISSUE TITLE
A socket V4 connection was reject

### ISSUE THREAD

**Issue by lowkeyfred** [librehat/shadowsocks-qt5#57]
Ubuntu 14.04
shadowsocksqt5 v0.9.2
I'd tried to apply
HTTP, HTTPS
 to system wide, and then it logged 
A socket V4 connection was reject
and I can not connect to blocked sites.
However, I use socket V5 in Proxy switchy.
Any fix?

**Comment by librehat** [comment]
Seems odd. Are you sure you're using socket v5?

**Comment by ikaryshin** [comment]
Also got the problem. I've got a solution. If you are using SwithyOmega on chrome, you should change the proxy from http(by default) to socks5. It works well for me.

**Comment by librehat** [comment]
@ikaryshin Of course you have to!!! This is a socks v5 proxy! Not a HTTP proxy!
