### ISSUE TITLE
客户端经常自动退出是怎么回事呢？

### ISSUE THREAD

**Issue by xiow** [librehat/shadowsocks-qt5#59]
win7 64
客户端0.9.2

最近几个新版本都有这问题、、

0.6貌似没事。。

**Comment by librehat** [comment]
What backend did you use?

**Comment by xiow** [comment]
https://github.com/librehat/shadowsocks-qt5/releases

http://ww3.sinaimg.cn/large/005vduMMgw1epmiw6fwzpj30py0fz75t.jpg

**Comment by librehat** [comment]
Backend!!! `libQtShadowsocks` or `shadowsocks-python` or whatever.

**Comment by xiow** [comment]
libQtShadowsocks

**Comment by librehat** [comment]
Does that happen if you use `win32` version?

**Comment by xiow** [comment]
呃。没试win32的版本、、我机子是win64的。。。
暂时换用shadowsocks-csharp了、、、

**Comment by librehat** [comment]
You can run `win32` on 64-bit version!

BTW, what is your encryption method?

**Comment by xiow** [comment]
aes-256-cfb

win64的电脑可以运行win 32 程序？、、我去试试

**Comment by xiow** [comment]
运行win32的也是那问题、、算了 不折腾了、直接换Shadowsocks-csharp了

**Comment by librehat** [comment]
你这叫我如何给你debug……
