### ISSUE TITLE
GLib-CRITICAL error on Ubuntu 14.10

### ISSUE THREAD

**Issue by zzt93** [librehat/shadowsocks-qt5#60]
An error message is : 
`GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed`

Besides, I follow the instruction of your installation, and run the command `ss-qt5` and start it. But I still can't not cross the FW. Firefow told me : 'The proxy server is refusing connections'.
I am sure the proxy setting is right.
Am do anything wrong? do I need install another backend? Thanks.

**Comment by zzt93** [comment]
Sorry, it can work. My browser's setting is wrong. But the error message is right.

**Comment by librehat** [comment]
What desktop environment are you using?

**Comment by librehat** [comment]
No more available information

**Comment by zzt93** [comment]
Sorry for being so so late, I using gnome 3 + unity.

**Comment by librehat** [comment]
Can you reproduce this error with latest version?

**Comment by zzt93** [comment]
No, I can't reproduce it now.
