### ISSUE TITLE
Autostart fails when Ubuntu has started although relative configuration seems correct 

### ISSUE THREAD

**Issue by SmilingSun** [librehat/shadowsocks-qt5#61]
I add ```ss-qt5``` to ```Startup Application Preferences```,

![startup applications preferences_126](https://cloud.githubusercontent.com/assets/4011348/6544334/39b6c82e-c586-11e4-9971-1aadd5f1884a.png)

and checked the option ```Autostart if profile is valid```,

![control panel shadowsocks-qt5_127](https://cloud.githubusercontent.com/assets/4011348/6544335/39b6d152-c586-11e4-845d-db4dfeed1f19.png)

 but when Ubuntu has finished booting, Shadowsocks profile remains stopped, I have to manually start the profile.

However, when I quit Shadowsocks-QT, and start it again, the option ``Autostart if profile is valid``` suceed as expected. 

Why ?

**Comment by librehat** [comment]
I tested the same configuration and it works as expected. (Fedora + Plasma 5)

Would you please paste your `.config/autostart/shadowsocks-qt5.desktop` content here? (the `ss-qt5` autostart file)

**Comment by SmilingSun** [comment]
No ```shadowsocks-qt5.desktop``` found in ```~/.config/autostart```, but ```start.sh.desktop```.



```
sunjizu@HP-Pavilion-g4-Notebook-PC:~/.config/autostart$ cat start.sh.desktop 
[Desktop Entry]
Type=Application
Exec=ss-qt5
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Shadowsocks
Name=Shadowsocks
Comment[en_US]=翻墙啊！
Comment=翻墙啊！
```

**Comment by librehat** [comment]
I have no idea. What desktop environment? Unity?

**Comment by SmilingSun** [comment]
Yes, Unity. 

This issue doesn't bother me too much, please ignore it without any other user report this issue.

**Comment by librehat** [comment]
I'll let this issue open until somebody willing to fix this.

There have been some trivial issues that only related to Ubuntu. Please, if you could, switch to other distributions, like Fedora or Arch.

**Comment by huyinjie** [comment]
On my Ubuntu 16.04 it works well now
![image](https://user-images.githubusercontent.com/8533957/37283592-7bcafba2-2633-11e8-8f5c-f83260d285f3.png)
