### ISSUE TITLE
A socket v4 connection was rejected

### ISSUE THREAD

**Issue by wzshuang** [librehat/shadowsocks-qt5#63]
Fedora21 google-chrome with SwitchySharp plugin.
background type is libQtShadowsocks.
what's the possible reason?

**Comment by librehat** [comment]
Please set your browser plugin (SwitchySharp) using socket **v5**!

**Comment by wzshuang** [comment]
sure it is socket v5. still doesn't work.

**Comment by librehat** [comment]
#57 Are you sure? Send a screenshoott of switchysharp configuration

**Comment by jp1017** [comment]
@librehat Thanks, it works. :smile: :+1: :100: :bouquet: https://github.com/shadowsocks/shadowsocks-qt5/issues/377
