### ISSUE TITLE
Delete-function does not work properly

### ISSUE THREAD

**Issue by YanceyWang** [librehat/shadowsocks-qt5#64]
Sometimes when i press `-`  button to delete a profile, the application window just disappears.
But sometimes it works fine.
I cant figure out why this happened。

**Comment by librehat** [comment]
I can't reproduce this issue. Maybe record a video and convert it to gif and paste here?

**Comment by SmilingSun** [comment]
I'm using Ubuntu, and the same thing happens. 
How to **record a video and convert it to gif and paste here?**

**Comment by librehat** [comment]
@SmilingSun http://linux.die.net/man/1/byzanz-record

**Comment by librehat** [comment]
Please supply more information, or this issue will be closed in next week.
