### ISSUE TITLE
No system tray icon on GNOME 3.14

### ISSUE THREAD

**Issue by Yayi** [librehat/shadowsocks-qt5#66]
gnome:3.14
qt:5.4
os:archlinux-x64

**Comment by librehat** [comment]
Did you choose system tray option?

![screenshot](https://cloud.githubusercontent.com/assets/1279432/6653764/226471e8-ca96-11e4-8b41-531fc36ff89b.png)

And you need to restart `ss-qt5` to let it take effect

**Comment by Yayi** [comment]
yes,i did,but have not effect.


                                                By:Yayi

2015-03-15 6:07 GMT+08:00 Symeon Huang <notifications@github.com>:

**Comment by Yayi** [comment]
like this
​


                                                By:Yayi

2015-03-15 15:02 GMT+08:00 Yayi <yz@yayi.biz>:

**Comment by librehat** [comment]
Don't reply via email! There is no screenshot here

**Comment by Yayi** [comment]
![2015-03-15 15 03 42](https://cloud.githubusercontent.com/assets/1091733/6655889/87a7da60-cb4d-11e4-9806-8823f21b9465.png)
sorry...
you can see the picture have not "ICON".

**Comment by librehat** [comment]
@Yayi What's `ss-qt5`'s version? And is anything else working correctly? (Is there an icon in the desktop notification?)

**Comment by Yayi** [comment]
@librehat other work is ok.have desktop notification,just say working or sotp.but have not icon.
ss-qt5:0.93
but 0.92 is same

**Comment by librehat** [comment]
@Yayi Did you install from AUR or compile from source yourself?

And check if there is `shadowsocks-qt5.png` in `/usr/share/icons/hicolor/512x512/apps/`

**Comment by Yayi** [comment]
@librehat compile from source myself,and i try copy shadowsocks-qt5.png to /usr/share/icons/hicolor/512x512/apps/ . but,not effect.

**Comment by librehat** [comment]
Weird. And other qt5 applications are working as expected?

**Comment by Yayi** [comment]
i have not other qt5 app......

**Comment by librehat** [comment]
Install `sni-qt` may solve this: https://github.com/owncloud/client/issues/2123#issuecomment-56964543

**Comment by Yayi** [comment]
i'm already installed,not effect.in the aur is same.
and i try the owncloud,it have icons.

**Comment by librehat** [comment]
run `ss-qt5` from terminal, is there any output?

**Comment by Yayi** [comment]
no,i thing this bug is qt5,the owncloud use qt4

**Comment by librehat** [comment]
Okay. I'll wait for more information about this issue.

**Comment by xgdgsc** [comment]
I tried with transmission-qt which is also qt5. It also has this bug. So I suspect it is a qt5 bug. But the existing related bugs in qt bugtracker are all marked as fixed. Maybe a regression.

**Comment by librehat** [comment]
@xgdgsc I suspect that is a GNOME issue. GNOME 3.16 was released a few days ago. Don't know if this issue persists on newer GNOME.

**Comment by librehat** [comment]
Does this issue persist in 2.0?

**Comment by xgdgsc** [comment]
I just tried with Gnome 3.16 and this 2.0. Still no tray icon, also with transmission-qt.

**Comment by librehat** [comment]
@xgdgsc Thanks. It seems a bug, either of Qt or GNOME 3 then.

**Comment by xgdgsc** [comment]
https://bugreports.qt.io/browse/QTBUG-32811
seems fixed in following qt versions.

**Comment by microcai** [comment]
这个不是 qt5 的 bug ,是 gnome 的 bug.

**Comment by microcai** [comment]
gnome should provide  SNI plugin for qt5 just like KDE does.

**Comment by xgdgsc** [comment]
Interesting thing is in gnome wayland session the icon shows.

**Comment by librehat** [comment]
I just found an old mail post: https://lists.fedoraproject.org/pipermail/devel/2014-March/196343.html

Would you please try to compile `ss-qt5` with `UBUNTU_UNITY` support? You have to install `libappindicator` from AUR at first. Then
```
qmake-qt5 DEFINES+="UBUNTU_UNITY"
make
make install
```

**Comment by librehat** [comment]
You may also need to install the application indicator extension: https://github.com/rgcjonas/gnome-shell-extension-appindicator

**Comment by xgdgsc** [comment]
I have shadowsocks-qt5 2.3.2. I confirm the qt 5.4.2 update fixes this.

**Comment by registe** [comment]
yes, don't need appindicator extensions, tray icon has already be fixed with gnome-shell-3.16.2 & qt 5.4.2 on Gentoo.

![screenshot-2015-06-23-17-06-36](https://cloud.githubusercontent.com/assets/458892/8302611/566ed5ae-19ca-11e5-85af-1e4a441b44c7.png)

**Comment by Kutear** [comment]
不能启动....点击程序鼠标等待了一会...就是起动不了

**Comment by librehat** [comment]
@Kutear 请重开一个新的issue好么？

**Comment by Halry** [comment]
在Fedora 22上面依然没有任何后台指示
