### ISSUE TITLE
Icon does not display normally after update

### ISSUE THREAD

**Issue by chihyang** [librehat/shadowsocks-qt5#71]
![shadowsock-qt5-icon-fault](https://cloud.githubusercontent.com/assets/3126902/6753460/16f30300-cf51-11e4-8546-4b174c9b7a95.png)
![shadowsock-qt5-icon-fault-2](https://cloud.githubusercontent.com/assets/3126902/6753685/d5fb8f82-cf52-11e4-91bb-9bcb0081f435.png)
As the pictures show, both the desktop and menu bar icon of shadowsocks-qt5 are blank after updating to the latest version 0.9.3 from 0.9.2. The OS is ubuntu 14.04 LTS.

**Comment by librehat** [comment]
I just forgot updating PPA. It was already fixed in master. The new version is building now. You'll be able to see icons in `0.9.3-2`

**Comment by chihyang** [comment]
Thanks!
