### ISSUE TITLE
[Ubuntu Only] Unable to display main window if autohide

### ISSUE THREAD

**Issue by heshunwq** [librehat/shadowsocks-qt5#72]
启动qt5之后，页面是这样的，我的系统 ubuntu kylin 14.10. 现在的问题是，我想要修改配置，或是编辑一些配置，应该在哪个文件中修改，也就是说qt5的配置文件路径是哪一个呢？
![shadowsocks](https://cloud.githubusercontent.com/assets/5101286/6795569/1071e900-d21d-11e4-91ba-792a08c18f0b.png)

**Comment by DrakeLeung** [comment]
我也遇到了这个issue :(

**Comment by librehat** [comment]
配置文件位置： `~/.config/shadowsocks/gui-config.json`

把你杂项里面的设置贴出来看看，还有是最新`0.9.4`版了吗？

**Comment by CzBiX** [comment]
Ubuntu 14.10 确认可以稳定复现，当启用了 autoHide 时会有问题。除了界面无法正常显示外，也无法正常退出。

**Comment by librehat** [comment]
@DrakeLeung @CzBiX  Is it only in `0.9.4`?

**Comment by CzBiX** [comment]
@librehat 之前用 0.9.2 的时候是启动后没有自动隐藏的问题.
升级到 0.9.4 之后可以在启动时自动隐藏了, 但是出现了现在这个问题.

**Comment by librehat** [comment]
@CzBiX I'm confused. So you can't autohide in `0.9.2`? Or say this issue is a totally regression?

**Comment by librehat** [comment]
@CzBiX Would you help me testing if commenting out line 54 in `main.cpp` (`w.hide()`) could solve this?

**Comment by CzBiX** [comment]
@librehat 注释后就回到了 0.9.2 的状态, 无法在启动时隐藏主界面, 但是可以正常显示界面.

**Comment by librehat** [comment]
Please try latest master code. I believe this time it'll be fixed.

**Comment by CzBiX** [comment]
@librehat 窗口是会自动隐藏了, 不过点击任务栏的 Show 不会显示窗口.
每次启动程序之后, 总共要点 3 次 Show 才能看到窗口.

**Comment by librehat** [comment]
@CzBiX 只有第一次要点三次吗?

**Comment by CzBiX** [comment]
@librehat 是的，在重新启动程序之前不会重复出现此问题。

**Comment by librehat** [comment]
Please try the latest code again.

**Comment by CzBiX** [comment]
@librehat 当前最新的代码不会在启动时隐藏窗口。

**Comment by librehat** [comment]
Try this patch: http://fpaste.org/205176/27797843/

**Comment by librehat** [comment]
That patch is included in `0.x` branch. `master` is now used to develop `v2.0`.

**Comment by Stephen-Chen** [comment]
我也在ubuntu下遇到了这个问题，能说明一下怎么解决吗？

**Comment by librehat** [comment]
@Stephen-Chen 你clone 0.x分支的代码，编译一下看看有没有用

**Comment by CzBiX** [comment]
@librehat 测试了下，还是无法在启动时隐藏窗口。

**Comment by librehat** [comment]
呃，不管了，至少窗口能正常显示了。得一门心思推进`2.0`的开发了。
