### ISSUE TITLE
Drop Ubuntu Unity specific code in 2.0

### ISSUE THREAD

**Issue by librehat** [librehat/shadowsocks-qt5#73]
It wastes time and energy to maintain a seperated Unity-specific system tray code. The upcoming Ubuntu 15.04 comes with Qt 5.4 which should resolve lots of system tray related issues. In that case, the Ubuntu Unity specific code might be dropped in the new 2.0 version.

Please comment below.

**Comment by vibbow** [comment]
于是你把14.04 LTS也放弃了？

**Comment by librehat** [comment]
@vibbow 为了支持Ubuntu就要写一堆dirty的code，然后这也把所有Debian系的都污染了，因为默认的规则就要写上UBUNTU_UNITY的DEFINE，在非Unity环境下就会各种乱套。

并不是放弃旧版的Ubuntu，而是放弃使用Unity桌面环境的Ubuntu 14.04和14.10

**Comment by vibbow** [comment]
不是所有人都用最新版的，我就喜欢用LTS的。

--- 原始邮件 ---

发件人： "Symeon Huang" <notifications@github.com>
已发： 2015年4月6日 12:34
收件人： "librehat/shadowsocks-qt5" <shadowsocks-qt5@noreply.github.com>
抄送： "vibbow" <vibbow@hotmail.com>
主题： Re: [shadowsocks-qt5] Drop Ubuntu Unity specific code in 2.0 (#73)

@vibbow 为了支持Ubuntu就要写一堆dirty的code，然后这也把所有Debian系的都污染了，因为默认的规则就要写上UBUNTU_UNITY的DEFINE，在非Unity环境下就会各种乱套。

并不是放弃旧版的Ubuntu，而是放弃使用Unity桌面环境的Ubuntu 14.04和14.10

---

**Comment by librehat** [comment]
@vibbow 那你也用Unity桌面么？

没办法，两权相害取其轻，为了更多广大非Unity的Ubuntu用户，以及所有其他Debian衍生发行版的用户，只能放弃掉一部分用户

**Comment by vibbow** [comment]
所以说这就是linux和windows之间的差距啊！





        通过 Android 版 Outlook 发送




On Mon, Apr 6, 2015 at 6:51 AM -0700, "Symeon Huang" <notifications@github.com> wrote:
@vibbow 那你也用Unity桌面么？

没办法，两权相害取其轻，为了更多广大非Unity的Ubuntu用户，以及所有其他Debian衍生发行版的用户，只能放弃掉一部分用户

---

**Comment by librehat** [comment]
The code is kept and improved. It'll determine if the DE is Unity.
