### ISSUE TITLE
使用 Google 搜索时报出异常流量预警

### ISSUE THREAD

**Issue by novembr0** [librehat/shadowsocks-qt5#74]
![baidushurufa_2015-4-7_14-53-0](https://cloud.githubusercontent.com/assets/4630628/7018392/3dc110a6-dd36-11e4-96bf-a94920c41fd7.png)
如图，通过 shadowsocks 使用 Google 搜索时出现流量异常预警，必须手动输入验证码才可以完成搜索，有遇到这个问题的吗？（shadowsocks-libev 运行于 debian 7 VPS 上）

**Comment by librehat** [comment]
这跟shadowsocks客户端有啥关系？就是谷歌说的，你服务器那个IP访问Google流量异常

**Comment by zhongjingwei** [comment]
@librehat 这个判断依据是什么

**Comment by edica02** [comment]
我用xxnet翻墙有时也出现这个情况。不知什么原因

**Comment by Arthur-Feng** [comment]
和你服务器同IP的同时访问Google太多或者用了程序大量抓取Google内容，Google认为这个IP的流量都是自动程序流量从而封锁。要不换服务器IP，要不换SS服务商，根本解决办法还是一个服务器不要太多人用。

**Comment by snowjade** [comment]
我是用ss翻墙上google的，跟题主遇到了同样的问题。

**Comment by huaijun-lee** [comment]
我也是这样，从vps供应商那买了之后，ss一直就是我一个人用，但还是要输验证码，而且谷歌显示的ip地址是北京朝阳区。。。。。

**Comment by jincdream** [comment]
vps 有问题。

**Comment by wangx1ng** [comment]
这个问题，很可能是同一 IP 段内的主机普遍被用作代理，我之前在digitalocean上，现在迁移到了 AWS EC2 上，没有再出现此类问题。如作者所说，和 shadowsocks client 没有关系。

**Comment by karymay** [comment]
可能是ss连接未正常关闭的bug。
