### ISSUE TITLE
2.0的刚刚更新，打开没有配置信息！

### ISSUE THREAD

**Issue by gengmu** [librehat/shadowsocks-qt5#76]
ubuntu14.10的

![2015-04-09 10 20 22](https://cloud.githubusercontent.com/assets/4141426/7059357/3e3fefc6-dea2-11e4-8b8f-5d3521832a77.png)

**Comment by wuzhizhan** [comment]
我的也有这个问题 ubuntu 14.04

**Comment by njdakula** [comment]
ubuntu 14.10

**Comment by laincat** [comment]
配置文件更换了。需要重新配置。

**Comment by iamdennisme** [comment]
我也有这个问题

**Comment by iamdennisme** [comment]
/.config/shadowsocks-qt5/  下面建立了config.ini  内容为
{
"***":"my name"  //***应该是配置名称，请问下配置规则是什么呢
"server":"XXXX",
"server_port":8080,
"local_port":1018,
"password":"XXXX",
"timeout":600,
"method":"ase-256-cfb",
"fast_open":ture
}

打开shadowsocks。并没有出现配置信息。

**Comment by laincat** [comment]
https://github.com/librehat/shadowsocks-qt5/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C

我是Windows下的，直接在界面下配置的。配置文件的服务器信息不是明文。。。我不清楚 ubuntu 下是不是了。。。

**Comment by iamdennisme** [comment]
以前是明文的

**Comment by librehat** [comment]
新的配置不是明文，为了方便，直接把class写入的，所以得重新配置。下一个版本可能会加入导入旧配置文件的功能。
