### ISSUE TITLE
Maybe some bugs in 2.0

### ISSUE THREAD

**Issue by jetz** [librehat/shadowsocks-qt5#77]
##### Update 2.0, some problems：

- Frozen my ubuntu 14.04.2 (unity) , so have to be forced to reboot, tried several times.
- Can't exit from system tray.
- Sometimes menus display, but most of the time not.
- Can only Add config by sudo.

Now, I have to use v0.9.5

**Comment by librehat** [comment]
On Ubuntu, I believe because of the global menu bar, the menu bar is displayed on the top of your desktop instead of in application.

I'll disable this function in next version to avoid this hassle.

not sure about the frozen issue.

**Comment by jetz** [comment]
Hi @librehat , start ss-qt5 in terminal, then show following logs:

![bug](https://cloud.githubusercontent.com/assets/1232624/7063208/4b896e16-ded7-11e4-8025-783d98387ef2.png)

The reason of those problems may be menu conflict,  just my guess. wait to try next version.

**Comment by q13** [comment]
+1

**Comment by librehat** [comment]
Please check #80

**Comment by librehat** [comment]
Other bugs should be resolved now.
