### ISSUE TITLE
QR code scan can not recognize server port sometimes

### ISSUE THREAD

**Issue by YanceyWang** [librehat/shadowsocks-qt5#78]
while scan on my  phone does well

**Comment by librehat** [comment]
Just server port?

Did you try use the image file directly?

**Comment by YanceyWang** [comment]
YOU don't actually got what i mean
Please refer to the picture
What i point out is the wrong indication of the `connect` and `disconnect` on the 2nd line.
![record](https://cloud.githubusercontent.com/assets/6010208/7081110/75f01d7e-df6f-11e4-91ab-b3d41bec213c.gif)

**Comment by librehat** [comment]
You pasted under a wrong issue. I know what you meant now, but I can't reproduce it on my platform. What distribution and desktop environment are you using?
