### ISSUE TITLE
Connecting indication may be wrong after some operations

### ISSUE THREAD

**Issue by YanceyWang** [librehat/shadowsocks-qt5#79]
reproduce steps
1.select one connections to connect
2.click **any other** connection to prompt the profile edit dialog
3.close the edit dialog 
then it indicates  the former connected connection in step 1 as **unconnected**, but it is being connected in fact.

**Comment by librehat** [comment]
I can't reproduce the issue.

You need to click one connection to see its status, if you just edit another connection, then all actions will represent the new connection instead of original one.
