### ISSUE TITLE
麻烦帮看下一下配置文件。

### ISSUE THREAD

**Issue by iamdennisme** [librehat/shadowsocks-qt5#80]
/.config/shadowsocks-qt5/  下面建立了config.ini  内容为
{
"***":"my name"  //***应该是配置名称项的name，请问下name是什么呢
"server":"XXXX",
"server_port":8080,
"local_port":1018,
"password":"XXXX",
"timeout":600,
"method":"ase-256-cfb",
"fast_open":ture
}

打开shadowsocks。并没有出现配置信息。
![2015-04-09 15 31 31](https://cloud.githubusercontent.com/assets/11866859/7062260/1647ee34-dece-11e4-88c7-1c995f85bfe8.png)

**Comment by librehat** [comment]
需要通过程序重新添加，配置文件格式不同了

**Comment by iamdennisme** [comment]
程序无法添加，按钮是置灰的

**Comment by librehat** [comment]
菜单栏，Ubuntu估计扔到顶部去了吧

**Comment by iamdennisme** [comment]
权限问题，搞定了，谢谢。

**Comment by librehat** [comment]
啥？应该不会存在权限问题才对

**Comment by iamdennisme** [comment]
我用sudo启动，就可以了

**Comment by librehat** [comment]
不需要sudo, 应该菜单栏是显示到Unity桌面顶部或者标题栏去了。

**Comment by iamdennisme** [comment]
显示了菜单栏，置灰了。我是ubuntu，不过用的gnome。自己按照第三种方法编译的

**Comment by librehat** [comment]
我看你的截图是只有工具栏（toolbar）啊，没有看到menu bar

**Comment by iamdennisme** [comment]
也是，不过我只要sudo就ok了

**Comment by iamdennisme** [comment]
每次必须用sudo启动，正常ss-qt5.就没有menu bar，同时配置也没有，刚sodo了一下，之前的配置没了。

**Comment by librehat** [comment]
@iamdennisme 你试试最新master分支的代码，我取消掉native menubar了，应该能正常显示在窗口里了。

**Comment by iamdennisme** [comment]
好的

**Comment by iamdennisme** [comment]
刚重新编译了，还是没显示，sudo就显示了

**Comment by librehat** [comment]
Try solutions here: https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

**Comment by iamdennisme** [comment]
ok了

**Comment by yulijia** [comment]
您好，我还有问题想请教一下

在我的系统中有menu bar，但是toolbar按钮是灰色的。在menu bar里connection里只有add和Test all connections latency可用(其他均为灰色)。用connection >> add >> manually创建一个成功的ss链接后，如果不设置自动启动连接并且重启软件，就根本无法连接上，因为下面toolbar (connect, disconnect, test latency)等等按钮都是灰色的。
os:fedora

![Imgur](http://i.imgur.com/FtgwLSE.png)

**Comment by librehat** [comment]
@yulijia 2.1版应该修复这个问题了，单击一下应该就能操作了

**Comment by yulijia** [comment]
@librehat  after updating  to 2.1 version, everything is great. Thanks a lot!

**Comment by ChengDaHaI** [comment]
Thanks!
