### ISSUE TITLE
cannot connect to shadowsocks server

### ISSUE THREAD

**Issue by whiteear** [librehat/shadowsocks-qt5#83]
anything works fine with previous version. after upgrade to 2.0 using apt-get. ss-qt doesnot work any more.

i have reconfigured the ss-qt 2.0 follow the guide in guide. the ss-qt reports "successfully connected", when i click the "connect" button. 

tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN      3537/ss-qt5     
tcp        0      0 127.0.0.1:1080          127.0.0.1:47036         TIME_WAIT   -               
tcp        0      0 127.0.0.1:1080          127.0.0.1:47019         TIME_WAIT   -               
tcp        0      0 127.0.0.1:1080          127.0.0.1:47039         TIME_WAIT   -     

but, the browser still doesnot open pages.
"ps" shows that the process started.
537  2165  0 09:12 ?        00:00:02 ss-qt5

Linux  3.16.0-33-generic #44-Ubuntu SMP Thu Mar 12 12:19:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ubuntu 14.10

**Comment by whiteear** [comment]
logs:

Initialising ciphers...
AES-256/CFB (AES-256-CFB) initialised.
Listen UDP socket state changed to QAbstractSocket::ClosingState 
Listen UDP socket state changed to QAbstractSocket::UnconnectedState 
Listen UDP socket state changed to QAbstractSocket::BoundState 
Running in local mode.
TCP server listen at port 1080
A new TCP connection.
Accept a local socket connection.
Connecting "www.gstatic.com" at port 80 from "127.0.0.1" at port 48299 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48302 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48304 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48306 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48308 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48310 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48312 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48314 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48316 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48318 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48320 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48322 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48324 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48326 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48328 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48330 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48333 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48335 
A new TCP connection.
Accept a local socket connection.
Connecting "accounts.google.com" at port 443 from "127.0.0.1" at port 48337

**Comment by librehat** [comment]
It seems you misconfigured or your server was down. The log shows that server didn't even respond.

**Comment by whiteear** [comment]
i'm sure the server works very well. i successfully connect it with shadowsocks-local-linux64 program. maybe misconfigured, so where can i find the configuration files? i fill all info exactly as wiki guided.

**Comment by librehat** [comment]
Edit the connection and check the server address and port
