### ISSUE TITLE
Connection button is disable every time starting the application

### ISSUE THREAD

**Issue by YanceyWang** [librehat/shadowsocks-qt5#84]
Another issue there
At start-up of the application, just close it and then start it,  all the buttons on the `2nd bar` are disable unless i open the edit dialog by double click one connections. you don't need actually do some modifications there just open the edit dialog  and close it . Then all the buttons become clickable.

![record](https://cloud.githubusercontent.com/assets/6010208/7081364/54f4e6e6-df73-11e4-971f-6a3d9b7a8330.gif)

**Comment by librehat** [comment]
No need to double click. One click is enough.
