### ISSUE TITLE
Crashed when trying to add a new profile

### ISSUE THREAD

**Issue by hulucc** [librehat/shadowsocks-qt5#86]
version ss-qt5-v2.0.0-win32
dump info:
eax=0285ff70 ebx=028392a0 ecx=0281b0c0 edx=00000010 esi=00000017 edi=00000000
eip=010ae6de esp=0022aa70 ebp=0022aa88 iopl=0         nv up ei pl nz na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010202
ss_qt5+0xcae6de:
010ae6de ff5604          call    dword ptr [esi+4]    ds:0023:0000001b=????????
stack:
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
0022aa88 0109c71c ss_qt5+0xcae6de
0022aaa8 00430211 ss_qt5+0xc9c71c
0022aaf8 005bb77a ss_qt5+0x30211
0022ad18 0108dc06 ss_qt5+0x1bb77a
0022ad58 00d8e6f9 ss_qt5+0xc8dc06
0022ae18 005bb77a ss_qt5+0x98e6f9
0022ae48 005c36a7 ss_qt5+0x1bb77a
0022ae98 01076a93 ss_qt5+0x1c36a7
0022aed8 005bb77a ss_qt5+0xc76a93
0022b0d8 00edd66c ss_qt5+0x1bb77a
0022b128 773a86ef ss_qt5+0xadd66c
0022b160 773a8876 user32!IsThreadDesktopComposited+0x11f
0022b1a4 773a881f user32!IsThreadDesktopComposited+0x2a6
0022b1ac 7774642e user32!IsThreadDesktopComposited+0x24f
00000000 00000000 ntdll!KiUserCallbackDispatcher+0x2e

**Comment by librehat** [comment]
Add new profile manually or by URI or scan QR code image?

**Comment by hulucc** [comment]
Adding new profile manually

**Comment by librehat** [comment]
Your OS version?

**Comment by hulucc** [comment]
win7 32bit

**Comment by librehat** [comment]
Can't reproduce your issues. I checked win32 build on my Windows 8.1, no crashes.

Reboot your computer and try the new build (2.1.0).
