### ISSUE TITLE
 升级之后无法使用

### ISSUE THREAD

**Issue by Stephen-Chen** [librehat/shadowsocks-qt5#87]
我升级软件后（新立得干的好事），软件变成了这样：
![](http://i2.tietuku.com/7d69d1fd527f82db.png)
而且任何按钮均无法点击

**Comment by yulijia** [comment]
I have the same problem, all buttons on the panel are grey. 
os: fedora20

**Comment by bsns** [comment]
After update the gui version,I can't enable the connection.

**Comment by librehat** [comment]
请先看2.0的更新说明，新版的配置和旧版不一样，所以空了。此外Ubuntu菜单栏不显示的问题见 #80
