### ISSUE TITLE
导入配置文件问题.

### ISSUE THREAD

**Issue by kxmp** [librehat/shadowsocks-qt5#89]
服务器端口全都是0,超时全都是10....本地地址也都空的...
重要的是密码也是错的...重输一下才能连上...
密码错误是在密码特别复杂的情况下才有的,里面有[ ` {

**Comment by librehat** [comment]
诶，我已经试过端口和超时没问题的啊。你原端口多少？
还有这个旧配置是ss-qt5的旧配置吗？

**Comment by kxmp** [comment]
{
"server" : "",
"server_port" : ,
"password" : "",
"method" : "",
"remarks" : ""}
这样的配置文件...

**Comment by librehat** [comment]
你那样的配置文件根本就不是`gui-config.json`啊，那是`config.json`吧，只有ss-qt5 0.x的配置文件能够这样导入，其他shadowsocks客户端的config.json还不能导入，下一个版本会加入的。
