### ISSUE TITLE
Cannot add new profile

### ISSUE THREAD

**Issue by ChengDaHaI** [librehat/shadowsocks-qt5#90]
![2015-04-13 10 16 43](https://cloud.githubusercontent.com/assets/11609265/7108920/3aa54466-e1c6-11e4-81d4-ae17055fbb25.png)
the button(connect, edit, and so on) cannot work,shown in the picture,and my OS is Ubuntu 14.04,the software version is 2.1.0

**Comment by librehat** [comment]
请先看wiki的常见问题好么
