### ISSUE TITLE
Cannot connect to multiple connections at the same time on some OSs

### ISSUE THREAD

**Issue by librehat** [librehat/shadowsocks-qt5#91]
On some platforms like Windows and some Linux distributions such as Ubuntu, if multiple connections are connected (with different local ports of course), only one will be usable.

This issue doesn't affect Fedora however (why?).

I already move controller to sub thread in latest code, but the issue persists. The issue might comes from `libQtShadowsocks`.

**Comment by librehat** [comment]
The latest code seems okay now. I just tested under Windows 8.1 and this issue is no longer bothering me.

If there are users encountering this problem after the next release (which will be `2.2.0`), please comment below with your operating system version, `ss-qt5` version and (for Linux distributions) `libQtShadowsocks` version.

**Comment by StrollStars** [comment]
Windows 7 64位还是无法连接多个服务器，只最后一个连接有效。

**Comment by librehat** [comment]
@StrollStars  实在太奇怪了，我在Windows 8.1 64位下试验了可以同时连接多个的（我在本地开了几个服务器然后同时连接的）。使用SwitchyOmega切换了好几次试验了好几个网站都没问题。不知道是不是平台相关，先继续保留这个问题直到有人知道怎么解决为止。

**Comment by librehat** [comment]
This is fixed in latest trunk of `libQtShadowsocks`. The windows pre-built binaries will be updated with next release of `ss-qt5`
