### ISSUE TITLE
Is it possible to use other crypto rather than botan?

### ISSUE THREAD

**Issue by Guenlay** [librehat/shadowsocks-qt5#95]
it doesnt properly support arm, that is not what a cross-platform application should be.

**Comment by librehat** [comment]
> it doesnt properly support arm,

Who says that? I have an ODROID-U3 board which uses botan without issues.

**Comment by Guenlay** [comment]
Well, i have an odroid-c1 with archlinux, it cant be compiled from aur package, looks like its arch's problem
